'use strict';var aa,ba=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},ca=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function da(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ea=da(this);function l(a,b){if(b)a:{var c=ea;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&ca(c,a,{configurable:!0,writable:!0,value:b})}}var fa;
if(typeof Object.setPrototypeOf=="function")fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa;
function p(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.ga=b.prototype}function la(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}
function q(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:la(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function ma(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");}function r(){this.D=!1;this.o=null;this.j=void 0;this.g=1;this.m=this.u=0;this.H=this.i=null}function na(a){if(a.D)throw new TypeError("Generator is already running");a.D=!0}
r.prototype.G=function(a){this.j=a};function oa(a,b){a.i={X:b,isException:!0};a.g=a.u||a.m}r.prototype.getNextAddressJsc=function(){return this.g};r.prototype.getYieldResultJsc=function(){return this.j};r.prototype.return=function(a){this.i={return:a};this.g=this.m};r.prototype["return"]=r.prototype.return;r.prototype.K=function(a){this.i={F:a};this.g=this.m};r.prototype.jumpThroughFinallyBlocks=r.prototype.K;r.prototype.h=function(a,b){this.g=b;return{value:a}};r.prototype.yield=r.prototype.h;
r.prototype.N=function(a,b){a=q(a);var c=a.next();ma(c);if(c.done)this.j=c.value,this.g=b;else return this.o=a,this.h(c.value,b)};r.prototype.yieldAll=r.prototype.N;r.prototype.F=function(a){this.g=a};r.prototype.jumpTo=r.prototype.F;r.prototype.C=function(){this.g=0};r.prototype.jumpToEnd=r.prototype.C;r.prototype.A=function(a,b){this.u=a;b!=void 0&&(this.m=b)};r.prototype.setCatchFinallyBlocks=r.prototype.A;r.prototype.M=function(a){this.u=0;this.m=a||0};r.prototype.setFinallyBlock=r.prototype.M;
r.prototype.B=function(a,b){this.g=a;this.u=b||0};r.prototype.leaveTryBlock=r.prototype.B;r.prototype.v=function(a){this.u=a||0;a=this.i.X;this.i=null;return a};r.prototype.enterCatchBlock=r.prototype.v;r.prototype.I=function(a,b,c){c?this.H[c]=this.i:this.H=[this.i];this.u=a||0;this.m=b||0};r.prototype.enterFinallyBlock=r.prototype.I;
r.prototype.L=function(a,b){b=this.H.splice(b||0)[0];(b=this.i=this.i||b)?b.isException?this.g=this.u||this.m:b.F!=void 0&&this.m<b.F?(this.g=b.F,this.i=null):this.g=this.m:this.g=a};r.prototype.leaveFinallyBlock=r.prototype.L;r.prototype.J=function(a){return new pa(a)};r.prototype.forIn=r.prototype.J;function pa(a){this.i=a;this.g=[];for(var b in a)this.g.push(b);this.g.reverse()}pa.prototype.h=function(){for(;this.g.length>0;){var a=this.g.pop();if(a in this.i)return a}return null};
pa.prototype.getNext=pa.prototype.h;function qa(a){this.g=new r;this.h=a}function ra(a,b){na(a.g);var c=a.g.o;if(c)return sa(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return ta(a)}function sa(a,b,c,d){try{var e=b.call(a.g.o,c);ma(e);if(!e.done)return a.g.D=!1,e;var f=e.value}catch(g){return a.g.o=null,oa(a.g,g),ta(a)}a.g.o=null;d.call(a.g,f);return ta(a)}
function ta(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.D=!1,{value:b.value,done:!1}}catch(c){a.g.j=void 0,oa(a.g,c)}a.g.D=!1;if(a.g.i){b=a.g.i;a.g.i=null;if(b.isException)throw b.X;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function ua(a){this.next=function(b){na(a.g);a.g.o?b=sa(a,a.g.o.next,b,a.g.G):(a.g.G(b),b=ta(a));return b};this.throw=function(b){na(a.g);a.g.o?b=sa(a,a.g.o["throw"],b,a.g.G):(oa(a.g,b),b=ta(a));return b};this.return=function(b){return ra(a,b)};this[Symbol.iterator]=function(){return this}}function va(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function f(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(f,e)}f(a.next())})}
function t(a){return va(new ua(new qa(a)))}l("Reflect.setPrototypeOf",function(a){return a?a:ka?function(b,c){try{return ka(b,c),!0}catch(d){return!1}}:null});
l("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.g=f;ca(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});
l("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");ca(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return wa(la(this))}});return a});function wa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
l("Promise",function(a){function b(g){this.h=0;this.i=void 0;this.g=[];this.u=!1;var h=this.j();try{g(h.resolve,h.reject)}catch(k){h.reject(k)}}function c(){this.g=null}function d(g){return g instanceof b?g:new b(function(h){h(g)})}if(a)return a;c.prototype.h=function(g){if(this.g==null){this.g=[];var h=this;this.i(function(){h.m()})}this.g.push(g)};var e=ea.setTimeout;c.prototype.i=function(g){e(g,0)};c.prototype.m=function(){for(;this.g&&this.g.length;){var g=this.g;this.g=[];for(var h=0;h<g.length;++h){var k=
g[h];g[h]=null;try{k()}catch(m){this.j(m)}}}this.g=null};c.prototype.j=function(g){this.i(function(){throw g;})};b.prototype.j=function(){function g(m){return function(n){k||(k=!0,m.call(h,n))}}var h=this,k=!1;return{resolve:g(this.D),reject:g(this.m)}};b.prototype.D=function(g){if(g===this)this.m(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.H(g);else{a:switch(typeof g){case "object":var h=g!=null;break a;case "function":h=!0;break a;default:h=!1}h?this.C(g):this.o(g)}};
b.prototype.C=function(g){var h=void 0;try{h=g.then}catch(k){this.m(k);return}typeof h=="function"?this.I(h,g):this.o(g)};b.prototype.m=function(g){this.v(2,g)};b.prototype.o=function(g){this.v(1,g)};b.prototype.v=function(g,h){if(this.h!=0)throw Error("Cannot settle("+g+", "+h+"): Promise already settled in state"+this.h);this.h=g;this.i=h;this.h===2&&this.G();this.B()};b.prototype.G=function(){var g=this;e(function(){if(g.A()){var h=ea.console;typeof h!=="undefined"&&h.error(g.i)}},1)};b.prototype.A=
function(){if(this.u)return!1;var g=ea.CustomEvent,h=ea.Event,k=ea.dispatchEvent;if(typeof k==="undefined")return!0;typeof g==="function"?g=new g("unhandledrejection",{cancelable:!0}):typeof h==="function"?g=new h("unhandledrejection",{cancelable:!0}):(g=ea.document.createEvent("CustomEvent"),g.initCustomEvent("unhandledrejection",!1,!0,g));g.promise=this;g.reason=this.i;return k(g)};b.prototype.B=function(){if(this.g!=null){for(var g=0;g<this.g.length;++g)f.h(this.g[g]);this.g=null}};var f=new c;
b.prototype.H=function(g){var h=this.j();g.R(h.resolve,h.reject)};b.prototype.I=function(g,h){var k=this.j();try{g.call(h,k.resolve,k.reject)}catch(m){k.reject(m)}};b.prototype.then=function(g,h){function k(y,A){return typeof y=="function"?function(G){try{m(y(G))}catch(D){n(D)}}:A}var m,n,w=new b(function(y,A){m=y;n=A});this.R(k(g,m),k(h,n));return w};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.R=function(g,h){function k(){switch(m.h){case 1:g(m.i);break;case 2:h(m.i);break;
default:throw Error("Unexpected state: "+m.h);}}var m=this;this.g==null?f.h(k):this.g.push(k);this.u=!0};b.resolve=d;b.reject=function(g){return new b(function(h,k){k(g)})};b.race=function(g){return new b(function(h,k){for(var m=q(g),n=m.next();!n.done;n=m.next())d(n.value).R(h,k)})};b.all=function(g){var h=q(g),k=h.next();return k.done?d([]):new b(function(m,n){function w(G){return function(D){y[G]=D;A--;A==0&&m(y)}}var y=[],A=0;do y.push(void 0),A++,d(k.value).R(w(y.length-1),n),k=h.next();while(!k.done)})};
return b});l("Object.setPrototypeOf",function(a){return a||ka});function u(a,b){return Object.prototype.hasOwnProperty.call(a,b)}var xa=typeof Object.assign=="function"?Object.assign:function(a,b){if(a==null)throw new TypeError("No nullish arg");a=Object(a);for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)u(d,e)&&(a[e]=d[e])}return a};l("Object.assign",function(a){return a||xa});
l("WeakMap",function(a){function b(k){this.g=(h+=Math.random()+1).toString();if(k){k=q(k);for(var m;!(m=k.next()).done;)m=m.value,this.set(m[0],m[1])}}function c(){}function d(k){var m=typeof k;return m==="object"&&k!==null||m==="function"}function e(k){if(!u(k,g)){var m=new c;ca(k,g,{value:m})}}function f(k){var m=Object[k];m&&(Object[k]=function(n){if(n instanceof c)return n;Object.isExtensible(n)&&e(n);return m(n)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),m=Object.seal({}),
n=new a([[k,2],[m,3]]);if(n.get(k)!=2||n.get(m)!=3)return!1;n.delete(k);n.set(m,4);return!n.has(k)&&n.get(m)==4}catch(w){return!1}}())return a;var g="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var h=0;b.prototype.set=function(k,m){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!u(k,g))throw Error("WeakMap key fail: "+k);k[g][this.g]=m;return this};b.prototype.get=function(k){return d(k)&&u(k,g)?k[g][this.g]:void 0};b.prototype.has=function(k){return d(k)&&u(k,
g)&&u(k[g],this.g)};b.prototype.delete=function(k){return d(k)&&u(k,g)&&u(k[g],this.g)?delete k[g][this.g]:!1};return b});
l("Map",function(a){function b(){var h={};return h.previous=h.next=h.head=h}function c(h,k){var m=h[1];return wa(function(){if(m){for(;m.head!=h[1];)m=m.previous;for(;m.next!=m.head;)return m=m.next,{done:!1,value:k(m)};m=null}return{done:!0,value:void 0}})}function d(h,k){var m=k&&typeof k;m=="object"||m=="function"?f.has(k)?m=f.get(k):(m=""+ ++g,f.set(k,m)):m="p_"+k;var n=h[0][m];if(n&&u(h[0],m))for(h=0;h<n.length;h++){var w=n[h];if(k!==k&&w.key!==w.key||k===w.key)return{id:m,list:n,index:h,entry:w}}return{id:m,
list:n,index:-1,entry:void 0}}function e(h){this[0]={};this[1]=b();this.size=0;if(h){h=q(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var h=Object.seal({x:4}),k=new a(q([[h,"s"]]));if(k.get(h)!="s"||k.size!=1||k.get({x:4})||k.set({x:4},"t")!=k||k.size!=2)return!1;var m=k.entries(),n=m.next();if(n.done||n.value[0]!=h||n.value[1]!="s")return!1;n=m.next();return n.done||n.value[0].x!=
4||n.value[1]!="t"||!m.next().done?!1:!0}catch(w){return!1}}())return a;var f=new WeakMap;e.prototype.set=function(h,k){h=h===0?0:h;var m=d(this,h);m.list||(m.list=this[0][m.id]=[]);m.entry?m.entry.value=k:(m.entry={next:this[1],previous:this[1].previous,head:this[1],key:h,value:k},m.list.push(m.entry),this[1].previous.next=m.entry,this[1].previous=m.entry,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.entry&&h.list?(h.list.splice(h.index,1),h.list.length||delete this[0][h.id],
h.entry.previous.next=h.entry.next,h.entry.next.previous=h.entry.previous,h.entry.head=null,this.size--,!0):!1};e.prototype.clear=function(){this[0]={};this[1]=this[1].previous=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).entry};e.prototype.get=function(h){return(h=d(this,h).entry)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,
function(h){return h.value})};e.prototype.forEach=function(h,k){for(var m=this.entries(),n;!(n=m.next()).done;)n=n.value,h.call(k,n[1],n[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var g=0;return e});
l("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(h){return h};var e=[],f=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof f=="function"){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});l("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)u(b,d)&&c.push([d,b[d]]);return c}});
l("Number.isFinite",function(a){return a?a:function(b){return typeof b!=="number"?!1:!isNaN(b)&&b!==Infinity&&b!==-Infinity}});l("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});l("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991});l("Number.isInteger",function(a){return a?a:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}});l("Number.isSafeInteger",function(a){return a?a:function(b){return Number.isInteger(b)&&Math.abs(b)<=Number.MAX_SAFE_INTEGER}});
l("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});l("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(c<0&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
l("String.prototype.includes",function(a){return a?a:function(b,c){if(this==null)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return this.indexOf(b,c||0)!==-1}});
function ya(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}l("Array.prototype.entries",function(a){return a?a:function(){return ya(this,function(b,c){return[b,c]})}});l("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||b===Infinity||b===-Infinity||b===0)return b;var c=Math.floor(Math.abs(b));return b<0?-c:c}});
l("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var g=d[f];if(b.call(c,g,f,d)){b=g;break a}}b=void 0}return b}});l("Number.isNaN",function(a){return a?a:function(b){return typeof b==="number"&&isNaN(b)}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var za=this||self;function Aa(a,b){a:{var c=["CLOSURE_FLAGS"];for(var d=za,e=0;e<c.length;e++)if(d=d[c[e]],d==null){c=null;break a}c=d}a=c&&c[a];return a!=null?a:b}function Ba(a){return a};var Ca=Aa(610401301,!1),Da=Aa(748402147,!0);function Ea(){return typeof BigInt==="function"};function Fa(a){a.ca=!0;return a};var Ga=Fa(function(a){return typeof a==="number"}),Ha=Fa(function(a){return typeof a==="string"}),Ia=Fa(function(a){return typeof a==="boolean"});var Ja=typeof za.BigInt==="function"&&typeof za.BigInt(0)==="bigint";function Ka(a){var b=a;if(Ha(b)){if(!/^\s*(?:-?[1-9]\d*|0)?\s*$/.test(b))throw Error(String(b));}else if(Ga(b)&&!Number.isSafeInteger(b))throw Error(String(b));return Ja?BigInt(a):a=Ia(a)?a?"1":"0":Ha(a)?a.trim()||"0":String(a)}var Qa=Fa(function(a){return Ja?a>=La&&a<=Ma:a[0]==="-"?Na(a,Oa):Na(a,Pa)}),Oa=Number.MIN_SAFE_INTEGER.toString(),La=Ja?BigInt(Number.MIN_SAFE_INTEGER):void 0,Pa=Number.MAX_SAFE_INTEGER.toString(),Ma=Ja?BigInt(Number.MAX_SAFE_INTEGER):void 0;
function Na(a,b){if(a.length>b.length)return!1;if(a.length<b.length||a===b)return!0;for(var c=0;c<a.length;c++){var d=a[c],e=b[c];if(d>e)return!1;if(d<e)return!0}};var Ra=typeof Uint8Array.prototype.slice==="function",v=0,x=0,Sa;function Ta(a){var b=a>>>0;v=b;x=(a-b)/4294967296>>>0}function Ua(a){if(a<0){Ta(-a);var b=q(Va(v,x));a=b.next().value;b=b.next().value;v=a>>>0;x=b>>>0}else Ta(a)}function Wa(a){var b=Sa||(Sa=new DataView(new ArrayBuffer(8)));b.setFloat32(0,+a,!0);x=0;v=b.getUint32(0,!0)}function Xa(a){var b=Sa||(Sa=new DataView(new ArrayBuffer(8)));b.setFloat64(0,+a,!0);v=b.getUint32(0,!0);x=b.getUint32(4,!0)}
function Ya(a,b){var c=b*4294967296+(a>>>0);return Number.isSafeInteger(c)?c:Za(a,b)}function $a(a,b){return Ka(Ea()?BigInt.asUintN(64,(BigInt(b>>>0)<<BigInt(32))+BigInt(a>>>0)):Za(a,b))}function ab(a,b){return Ea()?Ka(BigInt.asIntN(64,(BigInt.asUintN(32,BigInt(b))<<BigInt(32))+BigInt.asUintN(32,BigInt(a)))):Ka(bb(a,b))}
function Za(a,b){b>>>=0;a>>>=0;if(b<=2097151)var c=""+(4294967296*b+a);else Ea()?c=""+(BigInt(b)<<BigInt(32)|BigInt(a)):(c=(a>>>24|b<<8)&16777215,b=b>>16&65535,a=(a&16777215)+c*6777216+b*6710656,c+=b*8147497,b*=2,a>=1E7&&(c+=a/1E7>>>0,a%=1E7),c>=1E7&&(b+=c/1E7>>>0,c%=1E7),c=b+cb(c)+cb(a));return c}function cb(a){a=String(a);return"0000000".slice(a.length)+a}
function bb(a,b){b&2147483648?Ea()?a=""+(BigInt(b|0)<<BigInt(32)|BigInt(a>>>0)):(b=q(Va(a,b)),a=b.next().value,b=b.next().value,a="-"+Za(a,b)):a=Za(a,b);return a}
function db(a){if(a.length<16)Ua(Number(a));else if(Ea())a=BigInt(a),v=Number(a&BigInt(4294967295))>>>0,x=Number(a>>BigInt(32)&BigInt(4294967295));else{var b=+(a[0]==="-");x=v=0;for(var c=a.length,d=b,e=(c-b)%6+b;e<=c;d=e,e+=6)d=Number(a.slice(d,e)),x*=1E6,v=v*1E6+d,v>=4294967296&&(x+=Math.trunc(v/4294967296),x>>>=0,v>>>=0);b&&(b=q(Va(v,x)),a=b.next().value,b=b.next().value,v=a,x=b)}}function Va(a,b){b=~b;a?a=~a+1:b+=1;return[a,b]};function eb(a,b){this.h=a>>>0;this.g=b>>>0}function fb(a){return a.h===0?new eb(0,1+~a.g):new eb(~a.h+1,~a.g)}function gb(a){hb();if(a>=ib&&a<=jb)return kb(Number(a));a=BigInt.asUintN(64,a);return new eb(Number(a&lb),Number(a>>mb))}function nb(a){if(!a)return ob||(ob=new eb(0,0));if(!/^\d+$/.test(a))return null;db(a);return new eb(v,x)}function kb(a){return new eb(a&4294967295,Math.floor(a/4294967296))}var ob;function pb(a,b){this.h=a>>>0;this.g=b>>>0}
function qb(a){hb();if(a>=ib&&a<=jb)return a=Number(a),new pb(a&4294967295,Math.floor(a/4294967296));a=BigInt.asUintN(64,a);return new pb(Number(a&lb),Number(a>>mb))}function rb(a){if(!a)return sb||(sb=new pb(0,0));if(!/^-?\d+$/.test(a))return null;db(a);return new pb(v,x)}var sb,tb=!1,ib,jb,lb,mb;function hb(){tb||(ib=BigInt(Number.MIN_SAFE_INTEGER),jb=BigInt(Number.MAX_SAFE_INTEGER),lb=BigInt(4294967295),mb=BigInt(32),tb=!0)};function ub(){throw Error("Invalid UTF8");}function vb(a,b){b=String.fromCharCode.apply(null,b);return a==null?b:a+b}var wb=void 0,xb,yb=typeof TextDecoder!=="undefined",zb,Ab=typeof String.prototype.isWellFormed==="function",Bb=typeof TextEncoder!=="undefined";
function Cb(a){var b=!1;b=b===void 0?!1:b;if(Bb){if(b&&(Ab?!a.isWellFormed():/(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])/.test(a)))throw Error("Found an unpaired surrogate");a=(zb||(zb=new TextEncoder)).encode(a)}else{for(var c=0,d=new Uint8Array(3*a.length),e=0;e<a.length;e++){var f=a.charCodeAt(e);if(f<128)d[c++]=f;else{if(f<2048)d[c++]=f>>6|192;else{if(f>=55296&&f<=57343){if(f<=56319&&e<a.length){var g=a.charCodeAt(++e);if(g>=56320&&g<=57343){f=(f-55296)*1024+g-56320+
65536;d[c++]=f>>18|240;d[c++]=f>>12&63|128;d[c++]=f>>6&63|128;d[c++]=f&63|128;continue}else e--}if(b)throw Error("Found an unpaired surrogate");f=65533}d[c++]=f>>12|224;d[c++]=f>>6&63|128}d[c++]=f&63|128}}a=c===d.length?d:d.subarray(0,c)}return a};function Db(a){za.setTimeout(function(){throw a;},0)};function Eb(){var a=za.navigator;return a&&(a=a.userAgent)?a:""}var Fb,Gb=za.navigator;Fb=Gb?Gb.userAgentData||null:null;var Hb={},Ib=null;function Jb(a){var b=a.length,c=b*3/4;c%3?c=Math.floor(c):"=.".indexOf(a[b-1])!=-1&&(c="=.".indexOf(a[b-2])!=-1?c-2:c-1);var d=new Uint8Array(c),e=0;Kb(a,function(f){d[e++]=f});return e!==c?d.subarray(0,e):d}
function Kb(a,b){function c(k){for(;d<a.length;){var m=a.charAt(d++),n=Ib[m];if(n!=null)return n;if(!/^[\s\xa0]*$/.test(m))throw Error("Unknown base64 encoding at char: "+m);}return k}Lb();for(var d=0;;){var e=c(-1),f=c(0),g=c(64),h=c(64);if(h===64&&e===-1)break;b(e<<2|f>>4);g!=64&&(b(f<<4&240|g>>2),h!=64&&b(g<<6&192|h))}}
function Lb(){if(!Ib){Ib={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;c<5;c++){var d=a.concat(b[c].split(""));Hb[c]=d;for(var e=0;e<d.length;e++){var f=d[e];Ib[f]===void 0&&(Ib[f]=e)}}}};var Mb=typeof Uint8Array!=="undefined",Nb=!(Ca&&Fb&&Fb.brands.length>0?0:Eb().indexOf("Trident")!=-1||Eb().indexOf("MSIE")!=-1)&&typeof btoa==="function",Ob=/[-_.]/g,Pb={"-":"+",_:"/",".":"="};function Rb(a){return Pb[a]||""}function Sb(a){if(!Nb)return Jb(a);a=Ob.test(a)?a.replace(Ob,Rb):a;a=atob(a);for(var b=new Uint8Array(a.length),c=0;c<a.length;c++)b[c]=a.charCodeAt(c);return b}var Tb={};function Ub(a,b){Vb(b);this.g=a;if(a!=null&&a.length===0)throw Error("ByteString should be constructed with non-empty values");}function Wb(){return Xb||(Xb=new Ub(null,Tb))}function Yb(a){Vb(Tb);var b=a.g;b=b==null||Mb&&b!=null&&b instanceof Uint8Array?b:typeof b==="string"?Sb(b):null;return b==null?b:a.g=b}var Xb;function Vb(a){if(a!==Tb)throw Error("illegal external caller");};function Zb(a,b,c){this.buffer=a;if(c&&!b)throw Error();this.g=b}
function $b(a,b){if(typeof a==="string")return new Zb(Sb(a),b);if(Array.isArray(a))return new Zb(new Uint8Array(a),b);if(a.constructor===Uint8Array)return new Zb(a,!1);if(a.constructor===ArrayBuffer)return a=new Uint8Array(a),new Zb(a,!1);if(a.constructor===Ub)return b=Yb(a)||new Uint8Array(0),new Zb(b,!0,a);if(a instanceof Uint8Array)return a=a.constructor===Uint8Array?a:new Uint8Array(a.buffer,a.byteOffset,a.byteLength),new Zb(a,!1);throw Error();};function ac(a,b,c,d){this.h=null;this.m=!1;this.g=this.i=this.j=0;this.init(a,b,c,d)}ac.prototype.init=function(a,b,c,d){var e=d===void 0?{}:d;d=e.P===void 0?!1:e.P;e=e.S===void 0?!1:e.S;this.P=d;this.S=e;a&&(a=$b(a,this.S),this.h=a.buffer,this.m=a.g,this.j=b||0,this.i=c!==void 0?this.j+c:this.h.length,this.g=this.j)};ac.prototype.clear=function(){this.h=null;this.m=!1;this.g=this.i=this.j=0;this.P=!1};
function bc(a,b){var c=0,d=0,e=0,f=a.h,g=a.g;do{var h=f[g++];c|=(h&127)<<e;e+=7}while(e<32&&h&128);if(e>32)for(d|=(h&127)>>4,e=3;e<32&&h&128;e+=7)h=f[g++],d|=(h&127)<<e;cc(a,g);if(!(h&128))return b(c>>>0,d>>>0);throw Error();}function cc(a,b){a.g=b;if(b>a.i)throw Error();}
function dc(a){var b=a.h,c=a.g,d=b[c++],e=d&127;if(d&128&&(d=b[c++],e|=(d&127)<<7,d&128&&(d=b[c++],e|=(d&127)<<14,d&128&&(d=b[c++],e|=(d&127)<<21,d&128&&(d=b[c++],e|=d<<28,d&128&&b[c++]&128&&b[c++]&128&&b[c++]&128&&b[c++]&128&&b[c++]&128)))))throw Error();cc(a,c);return e}function ec(a){return dc(a)>>>0}function fc(a){a=ec(a);return a>>>1^-(a&1)}function hc(a){return bc(a,ab)}function ic(a){var b=a.h,c=a.g,d=b[c],e=b[c+1],f=b[c+2];b=b[c+3];cc(a,a.g+4);return(d<<0|e<<8|f<<16|b<<24)>>>0}
function jc(a){var b=ic(a);a=(b>>31)*2+1;var c=b>>>23&255;b&=8388607;return c==255?b?NaN:a*Infinity:c==0?a*1.401298464324817E-45*b:a*Math.pow(2,c-150)*(b+8388608)}function kc(a){var b=ic(a),c=ic(a);a=(c>>31)*2+1;var d=c>>>20&2047;b=4294967296*(c&1048575)+b;return d==2047?b?NaN:a*Infinity:d==0?a*4.9E-324*b:a*Math.pow(2,d-1075)*(b+4503599627370496)}function lc(a){for(var b=0,c=a.g,d=c+10,e=a.h;c<d;){var f=e[c++];b|=f;if((f&128)===0)return cc(a,c),!!(b&127)}throw Error();}
function mc(a){return dc(a)}function nc(a,b){if(b<0)throw Error();var c=a.g;b=c+b;if(b>a.i)throw Error();a.g=b;return c}function oc(a,b){if(b==0)return Wb();var c=nc(a,b);a.P&&a.m?c=a.h.subarray(c,c+b):(a=a.h,b=c+b,c=c===b?new Uint8Array(0):Ra?a.slice(c,b):new Uint8Array(a.subarray(c,b)));return c.length==0?Wb():new Ub(c,Tb)}var pc=[],qc=void 0;function rc(){this.g=[]}rc.prototype.length=function(){return this.g.length};rc.prototype.end=function(){var a=this.g;this.g=[];return a};function sc(a,b,c){for(;c>0||b>127;)a.g.push(b&127|128),b=(b>>>7|c<<25)>>>0,c>>>=7;a.g.push(b)}function tc(a,b){for(;b>127;)a.g.push(b&127|128),b>>>=7;a.g.push(b)}function uc(a,b){if(b>=0)tc(a,b);else{for(var c=0;c<9;c++)a.g.push(b&127|128),b>>=7;a.g.push(1)}}function z(a,b){a.g.push(b>>>0&255);a.g.push(b>>>8&255);a.g.push(b>>>16&255);a.g.push(b>>>24&255)};function vc(a,b,c,d){if(pc.length){var e=pc.pop();e.init(a,b,c,d);a=e}else a=new ac(a,b,c,d);this.g=a;this.j=this.g.g;this.h=this.i=-1;this.setOptions(d)}vc.prototype.setOptions=function(a){a=a===void 0?{}:a;this.U=a.U===void 0?!1:a.U};function wc(a,b,c,d){if(xc.length){var e=xc.pop();e.setOptions(d);e.g.init(a,b,c,d);return e}return new vc(a,b,c,d)}function yc(a){a.g.clear();a.i=-1;a.h=-1;xc.length<100&&xc.push(a)}
function zc(a){var b=a.g;if(b.g==b.i)return!1;a.j=a.g.g;var c=ec(a.g);b=c>>>3;c&=7;if(!(c>=0&&c<=5))throw Error();if(b<1)throw Error();a.i=b;a.h=c;return!0}function Ac(a){switch(a.h){case 0:a.h!=0?Ac(a):lc(a.g);break;case 1:a=a.g;cc(a,a.g+8);break;case 2:if(a.h!=2)Ac(a);else{var b=ec(a.g);a=a.g;cc(a,a.g+b)}break;case 5:a=a.g;cc(a,a.g+4);break;case 3:b=a.i;do{if(!zc(a))throw Error();if(a.h==4){if(a.i!=b)throw Error();break}Ac(a)}while(1);break;default:throw Error();}}
function Bc(a,b,c){var d=a.g.i,e=ec(a.g);e=a.g.g+e;var f=e-d;f<=0&&(a.g.i=e,c(b,a,void 0,void 0,void 0),f=e-a.g.g);if(f)throw Error();a.g.g=e;a.g.i=d;return b}
function Cc(a){var b=ec(a.g);a=a.g;var c=nc(a,b);a=a.h;if(yb){var d=a,e;(e=xb)||(e=xb=new TextDecoder("utf-8",{fatal:!0}));b=c+b;d=c===0&&b===d.length?d:d.subarray(c,b);try{var f=e.decode(d)}catch(m){if(wb===void 0){try{e.decode(new Uint8Array([128]))}catch(n){}try{e.decode(new Uint8Array([97])),wb=!0}catch(n){wb=!1}}!wb&&(xb=void 0);throw m;}}else{f=c;b=f+b;c=[];for(var g=null,h,k;f<b;)h=a[f++],h<128?c.push(h):h<224?f>=b?ub():(k=a[f++],h<194||(k&192)!==128?(f--,ub()):c.push((h&31)<<6|k&63)):h<240?
f>=b-1?ub():(k=a[f++],(k&192)!==128||h===224&&k<160||h===237&&k>=160||((e=a[f++])&192)!==128?(f--,ub()):c.push((h&15)<<12|(k&63)<<6|e&63)):h<=244?f>=b-2?ub():(k=a[f++],(k&192)!==128||(h<<28)+(k-144)>>30!==0||((e=a[f++])&192)!==128||((d=a[f++])&192)!==128?(f--,ub()):(h=(h&7)<<18|(k&63)<<12|(e&63)<<6|d&63,h-=65536,c.push((h>>10&1023)+55296,(h&1023)+56320))):ub(),c.length>=8192&&(g=vb(g,c),c.length=0);f=vb(g,c)}return f}function Dc(a){var b=ec(a.g);return oc(a.g,b)}
function Ec(a,b,c){var d=ec(a.g);for(d=a.g.g+d;a.g.g<d;)c.push(b(a.g))}var xc=[];function Fc(){this.i=[];this.h=0;this.g=new rc}function Gc(a,b){b.length!==0&&(a.i.push(b),a.h+=b.length)}function Hc(a,b){B(a,b,2);b=a.g.end();Gc(a,b);b.push(a.h);return b}function Ic(a,b){var c=b.pop();for(c=a.h+a.g.length()-c;c>127;)b.push(c&127|128),c>>>=7,a.h++;b.push(c);a.h++}function B(a,b,c){tc(a.g,b*8+c)}function Jc(a,b,c){c!=null&&(c=parseInt(c,10),B(a,b,0),uc(a.g,c))}function Kc(a,b,c){B(a,b,2);tc(a.g,c.length);Gc(a,a.g.end());Gc(a,c)}
function Lc(a,b,c,d){c!=null&&(b=Hc(a,b),d(c,a),Ic(a,b))}function Mc(a){switch(typeof a){case "string":a.length&&a[0]==="-"?nb(a.substring(1)):nb(a)}};var Nc=typeof Symbol==="function"&&typeof Symbol()==="symbol";function Oc(a,b,c){return typeof Symbol==="function"&&typeof Symbol()==="symbol"?(c===void 0?0:c)&&Symbol.for&&a?Symbol.for(a):a!=null?Symbol(a):Symbol():b}var Pc=Oc("jas",void 0,!0),Qc=Oc(void 0,"1oa"),Rc=Oc(void 0,Symbol()),Sc=Oc(void 0,"0ubs"),Tc=Oc(void 0,"0ubsb"),Uc=Oc(void 0,"0actk"),Vc=Oc("m_m","da",!0);var Wc={ba:{value:0,configurable:!0,writable:!0,enumerable:!1}},Xc=Object.defineProperties,C=Nc?Pc:"ba",Yc,Zc=[];E(Zc,7);Yc=Object.freeze(Zc);function $c(a,b){Nc||C in a||Xc(a,Wc);a[C]|=b}function E(a,b){Nc||C in a||Xc(a,Wc);a[C]=b}function ad(a){$c(a,8192);return a};var bd={};function cd(a,b){return b===void 0?a.g!==dd&&!!(2&(a.l[C]|0)):!!(2&b)&&a.g!==dd}var dd={};function ed(a,b,c){var d=b&128?0:-1,e=a.length,f;if(f=!!e)f=a[e-1],f=f!=null&&typeof f==="object"&&f.constructor===Object;var g=e+(f?-1:0);for(b=b&128?1:0;b<g;b++)c(b-d,a[b]);if(f){a=a[e-1];for(var h in a)!isNaN(h)&&c(+h,a[h])}}var fd={};function kd(a){return a&128?fd:void 0};function ld(a){return a};var md=void 0;function nd(a,b){if(a!=null){var c;var d=(c=md)!=null?c:md={};c=d[a]||0;c>=b||(d[a]=c+1,a=Error(),a.__closure__error__context__984382||(a.__closure__error__context__984382={}),a.__closure__error__context__984382.severity="incident",Db(a))}};function od(a){return Array.prototype.slice.call(a)};var pd=typeof BigInt==="function"?BigInt.asIntN:void 0,qd=typeof BigInt==="function"?BigInt.asUintN:void 0,rd=Number.isSafeInteger,sd=Number.isFinite,td=Math.trunc;function ud(a){if(a!=null&&typeof a!=="number")throw Error("Value of float/double field must be a number, found "+typeof a+": "+a);return a}function vd(a){if(a==null||typeof a==="number")return a;if(a==="NaN"||a==="Infinity"||a==="-Infinity")return Number(a)}
function wd(a){if(a==null||typeof a==="boolean")return a;if(typeof a==="number")return!!a}var xd=/^-?([1-9][0-9]*|0)(\.[0-9]+)?$/;function yd(a){switch(typeof a){case "bigint":return!0;case "number":return sd(a);case "string":return xd.test(a);default:return!1}}function zd(a){if(a==null)return a;if(typeof a==="string"&&a)a=+a;else if(typeof a!=="number")return;return sd(a)?a|0:void 0}
function Ad(a){if(a==null)return a;if(typeof a==="string"&&a)a=+a;else if(typeof a!=="number")return;return sd(a)?a>>>0:void 0}
function Bd(a){if(a==null)return a;var b=typeof a;if(b==="bigint")return String(pd(64,a));if(yd(a)){if(b==="string")return b=td(Number(a)),rd(b)?a=String(b):(b=a.indexOf("."),b!==-1&&(a=a.substring(0,b)),b=a.length,(a[0]==="-"?b<20||b===20&&a<="-9223372036854775808":b<19||b===19&&a<="9223372036854775807")||(db(a),a=bb(v,x))),a;if(b==="number"){a=td(a);if(!rd(a)){Ua(a);b=v;var c=x;if(a=c&2147483648)b=~b+1>>>0,c=~c>>>0,b==0&&(c=c+1>>>0);b=Ya(b,c);a=typeof b==="number"?a?-b:b:a?"-"+b:b}return a}}}
function Cd(a){if(a==null)return a;var b=typeof a;if(b==="bigint")return String(qd(64,a));if(yd(a)){if(b==="string")return b=td(Number(a)),rd(b)&&b>=0?a=String(b):(b=a.indexOf("."),b!==-1&&(a=a.substring(0,b)),a[0]==="-"?b=!1:(b=a.length,b=b<20?!0:b===20&&a<="18446744073709551615"),b||(db(a),a=Za(v,x))),a;if(b==="number")return a=td(a),a>=0&&rd(a)||(Ua(a),a=Ya(v,x)),a}}function Dd(a){if(a==null||typeof a=="string"||a instanceof Ub)return a}
function Ed(a){if(a!=null&&typeof a!=="string")throw Error();return a}function Fd(a){return a==null||typeof a==="string"?a:void 0};function Gd(a){var b=Ba(Rc);return b?a[b]:void 0}function Hd(){}function Id(a,b){for(var c in a)!isNaN(c)&&b(a,+c,a[c])}function Jd(a){var b=new Hd;Id(a,function(c,d,e){b[d]=od(e)});b.g=a.g;return b}function Kd(a,b){b<100||nd(Sc,1)};function Ld(a,b,c,d){var e=d!==void 0;d=!!d;var f=Ba(Rc),g;!e&&Nc&&f&&(g=a[f])&&Id(g,Kd);f=[];var h=a.length;g=4294967295;var k=!1,m=!!(b&64),n=m?b&128?0:-1:void 0;if(!(b&1)){var w=h&&a[h-1];w!=null&&typeof w==="object"&&w.constructor===Object?(h--,g=h):w=void 0;if(m&&!(b&128)&&!e){k=!0;var y;g=((y=Md)!=null?y:ld)(g-n,n,a,w,void 0)+n}}b=void 0;for(y=0;y<h;y++){var A=a[y];if(A!=null&&(A=c(A,d))!=null)if(m&&y>=g){var G=y-n,D=void 0;((D=b)!=null?D:b={})[G]=A}else f[y]=A}if(w)for(var S in w)h=w[S],h!=
null&&(h=c(h,d))!=null&&(y=+S,A=void 0,m&&!Number.isNaN(y)&&(A=y+n)<g?f[A]=h:(y=void 0,((y=b)!=null?y:b={})[S]=h));b&&(k?f.push(b):f[g]=b);e&&Ba(Rc)&&(a=Gd(a))&&a instanceof Hd&&(f[Rc]=Jd(a));return f}
function Nd(a){switch(typeof a){case "number":return Number.isFinite(a)?a:""+a;case "bigint":return Qa(a)?Number(a):""+a;case "boolean":return a?1:0;case "object":if(Array.isArray(a)){var b=a[C]|0;return a.length===0&&b&1?void 0:Ld(a,b,Nd)}if(a!=null&&a[Vc]===bd)return Od(a);if(a instanceof Ub){b=a.g;if(b==null)a="";else if(typeof b==="string")a=b;else{if(Nb){for(var c="",d=0,e=b.length-10240;d<e;)c+=String.fromCharCode.apply(null,b.subarray(d,d+=10240));c+=String.fromCharCode.apply(null,d?b.subarray(d):
b);b=btoa(c)}else{c===void 0&&(c=0);Lb();c=Hb[c];d=Array(Math.floor(b.length/3));e=c[64]||"";for(var f=0,g=0;f<b.length-2;f+=3){var h=b[f],k=b[f+1],m=b[f+2],n=c[h>>2];h=c[(h&3)<<4|k>>4];k=c[(k&15)<<2|m>>6];m=c[m&63];d[g++]=n+h+k+m}n=0;m=e;switch(b.length-f){case 2:n=b[f+1],m=c[(n&15)<<2]||e;case 1:b=b[f],d[g]=c[b>>2]+c[(b&3)<<4|n>>4]+m+e}b=d.join("")}a=a.g=b}return a}return}return a}var Md;function Od(a){a=a.l;return Ld(a,a[C]|0,Nd)};var Pd,Qd;function Rd(a){switch(typeof a){case "boolean":return Pd||(Pd=[0,void 0,!0]);case "number":return a>0?void 0:a===0?Qd||(Qd=[0,void 0]):[-a,void 0];case "string":return[0,a];case "object":return a}}function Sd(a,b){return F(a,b[0],b[1])}
function F(a,b,c,d){d=d===void 0?0:d;if(a==null){var e=32;c?(a=[c],e|=128):a=[];b&&(e=e&-16760833|(b&1023)<<14)}else{if(!Array.isArray(a))throw Error("narr");e=a[C]|0;if(Da&&1&e)throw Error("rfarr");2048&e&&!(2&e)&&Td();if(e&256)throw Error("farr");if(e&64)return(e|d)!==e&&E(a,e|d),a;if(c&&(e|=128,c!==a[0]))throw Error("mid");a:{c=a;e|=64;var f=c.length;if(f){var g=f-1,h=c[g];if(h!=null&&typeof h==="object"&&h.constructor===Object){b=e&128?0:-1;g-=b;if(g>=1024)throw Error("pvtlmt");for(var k in h)f=
+k,f<g&&(c[f+b]=h[k],delete h[k]);e=e&-16760833|(g&1023)<<14;break a}}if(b){k=Math.max(b,f-(e&128?0:-1));if(k>1024)throw Error("spvt");e=e&-16760833|(k&1023)<<14}}}E(a,e|64|d);return a}function Td(){if(Da)throw Error("carr");nd(Uc,5)};function Ud(a,b){if(typeof a!=="object")return a;if(Array.isArray(a)){var c=a[C]|0;a.length===0&&c&1?a=void 0:c&2||(!b||4096&c||16&c?a=Vd(a,c,!1,b&&!(c&16)):($c(a,34),c&4&&Object.freeze(a)));return a}if(a!=null&&a[Vc]===bd)return b=a.l,c=b[C]|0,cd(a,c)?a:Wd(a,b,c)?Xd(a,b):Vd(b,c);if(a instanceof Ub)return a}function Xd(a,b,c){a=new a.constructor(b);c&&(a.g=dd);a.h=dd;return a}function Vd(a,b,c,d){d!=null||(d=!!(34&b));a=Ld(a,b,Ud,d);d=32;c&&(d|=2);b=b&16769217|d;E(a,b);return a}
function Yd(a){if(a.g!==dd)return!1;var b=a.l;b=Vd(b,b[C]|0);$c(b,2048);a.l=b;a.g=void 0;a.h=void 0;return!0}function Zd(a){if(!Yd(a)&&cd(a,a.l[C]|0))throw Error();}function $d(a,b){b===void 0&&(b=a[C]|0);b&32&&!(b&4096)&&E(a,b|4096)}function Wd(a,b,c){return c&2?!0:c&32&&!(c&4096)?(E(b,c|2),a.g=dd,!0):!1};function ae(a,b,c){a=be(a.l,b,void 0,c);if(a!==null)return a}function be(a,b,c,d){if(b===-1)return null;var e=b+(c?0:-1),f=a.length-1;if(!(f<1+(c?0:-1))){if(e>=f){var g=a[f];if(g!=null&&typeof g==="object"&&g.constructor===Object){c=g[b];var h=!0}else if(e===f)c=g;else return}else c=a[e];if(d&&c!=null){d=d(c);if(d==null)return d;if(!Object.is(d,c))return h?g[b]=d:a[e]=d,d}return c}}function ce(a,b,c){Zd(a);var d=a.l;H(d,d[C]|0,b,c);return a}
function H(a,b,c,d,e){var f=c+(e?0:-1),g=a.length-1;if(g>=1+(e?0:-1)&&f>=g){var h=a[g];if(h!=null&&typeof h==="object"&&h.constructor===Object)return h[c]=d,b}if(f<=g)return a[f]=d,b;if(d!==void 0){var k;g=((k=b)!=null?k:b=a[C]|0)>>14&1023||536870912;c>=g?d!=null&&(f={},a[g+(e?0:-1)]=(f[c]=d,f)):a[f]=d}return b}function de(a,b){return ee(a,a[C]|0,b)}function fe(a){return!!(2&a)&&!!(4&a)||!!(256&a)}
function ge(a){return a==null?a:typeof a==="string"?a?new Ub(a,Tb):Wb():a.constructor===Ub?a:Mb&&a!=null&&a instanceof Uint8Array?a.length?new Ub(new Uint8Array(a),Tb):Wb():void 0}function ee(a,b,c){if(b&2)throw Error();var d=kd(b);var e=be(a,c,d);e=Array.isArray(e)?e:Yc;var f=e===Yc?7:e[C]|0;var g=f;2&b&&(g|=2);g|=1;if(2&g||fe(g)||16&g)g===f||fe(g)||E(e,g),e=od(e),f=0,g=he(g,b),H(a,b,c,e,d);g&=-13;g!==f&&E(e,g);return e}
function ie(a,b,c,d){Zd(a);var e=a.l,f=e[C]|0;if(d==null){var g=je(e);if(ke(g,e,f,c)===b)g.set(c,0);else return a}else f=le(e,f,c,b);H(e,f,b,d);return a}function me(a,b,c,d){var e=a[C]|0,f=kd(e);e=le(a,e,c,b,f);H(a,e,b,d,f)}function je(a){if(Nc){var b;return(b=a[Qc])!=null?b:a[Qc]=new Map}if(Qc in a)return a[Qc];b=new Map;Object.defineProperty(a,Qc,{value:b});return b}function le(a,b,c,d,e){var f=je(a),g=ke(f,a,b,c,e);g!==d&&(g&&(b=H(a,b,g,void 0,e)),f.set(c,d));return b}
function ke(a,b,c,d,e){var f=a.get(d);if(f!=null)return f;for(var g=f=0;g<d.length;g++){var h=d[g];be(b,h,e)!=null&&(f!==0&&(c=H(b,c,f,void 0,e)),f=h)}a.set(d,f);return f}function ne(a,b,c){var d=a[C]|0,e=kd(d),f=be(a,c,e);if(f!=null&&f[Vc]===bd){if(!cd(f))return Yd(f),f.l;var g=f.l}else Array.isArray(f)&&(g=f);if(g){var h=g[C]|0;h&2&&(g=Vd(g,h))}g=Sd(g,b);g!==f&&H(a,d,c,g,e);return g}
function oe(a,b){var c=pe,d=!1,e=be(a,4,void 0,function(f){if(f!=null&&f[Vc]===bd)var g=f;else if(Array.isArray(f)){g=f[C]|0;var h=g|b&32;h|=b&2;h!==g&&E(f,h);g=new c(f)}else g=void 0;d=g!==f&&g!=null;return g});if(e!=null)return d&&!cd(e)&&$d(a,b),e}function qe(a){var b=a.l,c=b[C]|0,d=oe(b,c);if(d==null)return d;c=b[C]|0;if(!cd(a,c)){var e=d;var f=e.l,g=f[C]|0;e=cd(e,g)?Wd(e,f,g)?Xd(e,f,!0):new e.constructor(Vd(f,g,!1)):e;e!==d&&(Yd(a)&&(b=a.l,c=b[C]|0),d=e,c=H(b,c,4,d),$d(b,c))}return d}
function re(a){a==null&&(a=void 0);return a}function se(a,b,c){c=re(c);ce(a,b,c);c&&!cd(c)&&$d(a.l);return a}function te(a,b){Zd(a);var c=a.l,d=c[C]|0;if(b==null)return H(c,d,1),a;for(var e=b===Yc?7:b[C]|0,f=e,g=fe(e),h=g||Object.isFrozen(b),k=!0,m=!0,n=0;n<b.length;n++){var w=b[n];g||(w=cd(w),k&&(k=!w),m&&(m=w))}g||(e=k?13:5,e=m?e&-4097:e|4096);h&&e===f||(b=od(b),f=0,e=he(e,d));e!==f&&E(b,e);d=H(c,d,1,b);2&e||!(4096&e||16&e)||$d(c,d);return a}function he(a,b){return a=(2&b?a|2:a&-3)&-273};function I(a,b,c){this.l=F(a,b,c,2048)}I.prototype.toJSON=function(){var a=Od(this);return a};I.prototype[Vc]=bd;I.prototype.toString=function(){return this.l.toString()};function J(){function a(){throw Error();}Object.setPrototypeOf(a,a.prototype);return a}var ue=J(),ve=J(),we=J(),xe=J(),ye=J(),ze=J(),Ae=J(),Be=J(),Ce=J(),De=J();function Ee(a,b,c){this.g=a;this.h=b;a=Ba(ue);this.i=!!a&&c===a||!1}function Fe(a,b){var c=c===void 0?ue:c;return new Ee(a,b,c)}function Ge(a,b,c,d,e){Lc(a,c,He(b,d),e)}var Ie=Fe(function(a,b,c,d,e){if(a.h!==2)return!1;Bc(a,ne(b,d,c),e);return!0},Ge),Je=Fe(function(a,b,c,d,e){if(a.h!==2)return!1;Bc(a,ne(b,d,c),e);return!0},Ge),Ke=Symbol(),Le=Symbol(),Me=Symbol(),Ne=Symbol(),Oe=Symbol(),Pe,Qe;
function Re(a,b,c,d){var e=d[a];if(e)return e;e={};e.aa=d;e.O=Rd(d[0]);var f=d[1],g=1;f&&f.constructor===Object&&(e.V=f,f=d[++g],typeof f==="function"&&(e.Y=!0,Pe!=null||(Pe=f),Qe!=null||(Qe=d[g+1]),f=d[g+=2]));for(var h={};f&&Array.isArray(f)&&f.length&&typeof f[0]==="number"&&f[0]>0;){for(var k=0;k<f.length;k++)h[f[k]]=f;f=d[++g]}for(k=1;f!==void 0;){typeof f==="number"&&(k+=f,f=d[++g]);var m=void 0;if(f instanceof Ee)var n=f;else n=Ie,g--;f=void 0;if((f=n)==null?0:f.i){f=d[++g];m=d;var w=g;typeof f===
"function"&&(f=f(),m[w]=f);m=f}f=d[++g];w=k+1;typeof f==="number"&&f<0&&(w-=f,f=d[++g]);for(;k<w;k++){var y=h[k];m?c(e,k,n,m,y):b(e,k,n,y)}}return d[a]=e}function Se(a){return Array.isArray(a)?a[0]instanceof Ee?a:[Je,a]:[a,void 0]}function He(a,b){if(a instanceof I)return a.l;if(Array.isArray(a))return Sd(a,b)};function Te(a,b,c,d){var e=c.g;a[b]=d?function(f,g,h){return e(f,g,h,d)}:e}function Ue(a,b,c,d,e){var f=c.g,g,h;a[b]=function(k,m,n){return f(k,m,n,h||(h=Re(Le,Te,Ue,d).O),g||(g=Ve(d)),e)}}
function Ve(a){var b=a[Me];if(b!=null)return b;var c=Re(Le,Te,Ue,a);b=c.Y?function(d,e){return Pe(d,e,c)}:function(d,e){for(;zc(e)&&e.h!=4;){var f=e.i,g=c[f];if(g==null){var h=c.V;h&&(h=h[f])&&(h=We(h),h!=null&&(g=c[f]=h))}if(g==null||!g(e,d,f)){h=e;g=h.j;Ac(h);if(h.U)var k=void 0;else{var m=h.g.g-g;h.g.g=g;k=oc(h.g,m)}m=h=g=void 0;var n=d;k&&((g=(h=(m=n[Rc])!=null?m:n[Rc]=new Hd)[f])!=null?g:h[f]=[]).push(k)}}if(d=Gd(d))d.g=c.aa[Oe];return!0};a[Me]=b;a[Oe]=Xe.bind(a);return b}
function Xe(a,b,c,d){var e=this[Le],f=this[Me],g=Sd(void 0,e.O),h=Gd(a);if(h){var k=!1,m=e.V;if(m){e=function(G,D,S){if(S.length!==0)if(m[D])for(G=q(S),D=G.next();!D.done;D=G.next()){D=wc(D.value);try{k=!0,f(g,D)}finally{yc(D)}}else d==null||d(a,D,S)};if(b==null)Id(h,e);else if(h!=null){var n=h[b];n&&e(h,b,n)}if(k){var w=a[C]|0;if(w&2&&w&2048&&(c==null||!c.fa))throw Error();var y=kd(w),A=function(G,D){if(be(a,G,y)!=null)switch(c==null?void 0:c.ea){case 1:return;default:throw Error();}D!=null&&(w=
H(a,w,G,D,y));delete h[G]};b==null?ed(g,g[C]|0,function(G,D){A(G,D)}):A(b,be(g,b,y))}}}}function We(a){a=Se(a);var b=a[0].g;if(a=a[1]){var c=Ve(a),d=Re(Le,Te,Ue,a).O;return function(e,f,g){return b(e,f,g,d,c)}}return b};function Ye(a,b,c){a[b]=c.h}function Ze(a,b,c,d){var e,f,g=c.h;a[b]=function(h,k,m){return g(h,k,m,f||(f=Re(Ke,Ye,Ze,d).O),e||(e=$e(d)))}}function $e(a){var b=a[Ne];if(!b){var c=Re(Ke,Ye,Ze,a);b=function(d,e){return af(d,e,c)};a[Ne]=b}return b}function af(a,b,c){ed(a,a[C]|0,function(d,e){if(e!=null){var f=bf(c,d);f?f(b,e,d):d<500||nd(Tc,3)}});(a=Gd(a))&&Id(a,function(d,e,f){Gc(b,b.g.end());for(d=0;d<f.length;d++)Gc(b,Yb(f[d])||new Uint8Array(0))})}
function bf(a,b){var c=a[b];if(c)return c;if(c=a.V)if(c=c[b]){c=Se(c);var d=c[0].h;if(c=c[1]){var e=$e(c),f=Re(Ke,Ye,Ze,c).O;c=a.Y?Qe(f,e):function(g,h,k){return d(g,h,k,f,e)}}else c=d;return a[b]=c}};function K(a,b,c){if(Array.isArray(b)){var d=b[C]|0;if(d&4)return b;for(var e=0,f=0;e<b.length;e++){var g=a(b[e]);g!=null&&(b[f++]=g)}f<e&&(b.length=f);a=d|1;c&&(a=(a|4)&-1537);a!==d&&E(b,a);c&&a&2&&Object.freeze(b);return b}}function L(a,b,c){return new Ee(a,b,c)}function M(a,b,c){return new Ee(a,b,c)}function N(a,b,c){H(a,a[C]|0,b,c,kd(a[C]|0))}
var cf=Fe(function(a,b,c,d,e){if(a.h!==2)return!1;a=Bc(a,Sd([void 0,void 0],d),e);a=od(a);d=b[C]|0;e=kd(d);if(d&2)throw Error();var f=be(b,c,e);if(Array.isArray(f)){var g=f[C]|0;g&8192||E(f,g|=8192);if(g&2){f=od(f);for(g=0;g<f.length;g++){var h=f[g]=od(f[g]);if(Array.isArray(h[1])){var k=h[1];$c(k,34);h[1]=k}}f=ad(f);H(b,d,c,f,e)}f.push(a)}else H(b,d,c,ad([a]),e);return!0},function(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++){var g=b[f];Array.isArray(g)&&Lc(a,c,Sd(g,d),e)}ad(b)}});
function df(a,b,c){b=vd(b);b!=null&&(B(a,c,1),a=a.g,Xa(b),z(a,v),z(a,x))}function ef(a,b,c){b=vd(b);b!=null&&(B(a,c,5),a=a.g,Wa(b),z(a,v))}function ff(a,b,c){b=Bd(b);if(b!=null){switch(typeof b){case "string":rb(b)}if(b!=null)switch(B(a,c,0),typeof b){case "number":a=a.g;Ua(b);sc(a,v,x);break;case "bigint":c=qb(b);sc(a.g,c.h,c.g);break;default:c=rb(b),sc(a.g,c.h,c.g)}}}
function gf(a,b,c){b=Cd(b);if(b!=null){switch(typeof b){case "string":nb(b)}if(b!=null)switch(B(a,c,0),typeof b){case "number":a=a.g;Ua(b);sc(a,v,x);break;case "bigint":c=gb(b);sc(a.g,c.h,c.g);break;default:c=nb(b),sc(a.g,c.h,c.g)}}}function hf(a,b,c){b=zd(b);b!=null&&b!=null&&(B(a,c,0),uc(a.g,b))}function jf(a,b,c){b=wd(b);b!=null&&(B(a,c,0),a.g.g.push(b?1:0))}function kf(a,b,c){b=Fd(b);b!=null&&Kc(a,c,Cb(b))}function lf(a,b,c,d,e){Lc(a,c,He(b,d),e)}function mf(a,b,c){Jc(a,c,zd(b))}
function nf(a,b,c){if(a.h!==5&&a.h!==2)return!1;b=de(b,c);a.h==2?Ec(a,jc,b):b.push(jc(a.g));return!0}function of(a,b,c){if(a.h!==0)return!1;N(b,c,bc(a.g,$a));return!0}function pf(a,b,c){if(a.h!==0&&a.h!==2)return!1;b=de(b,c);a.h==2?Ec(a,dc,b):b.push(dc(a.g));return!0}function qf(a,b,c){if(a.h!==0&&a.h!==2)return!1;b=de(b,c);a.h==2?Ec(a,lc,b):b.push(lc(a.g));return!0}
var rf=L(function(a,b,c){if(a.h!==1)return!1;N(b,c,kc(a.g));return!0},df,Be),sf=L(function(a,b,c,d){if(a.h!==1)return!1;me(b,c,d,kc(a.g));return!0},df,Be),O=L(function(a,b,c){if(a.h!==5)return!1;N(b,c,jc(a.g));return!0},ef,Ae),tf=M(nf,function(a,b,c){b=K(vd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,5),e=e.g,Wa(g),z(e,v))}},Ae),P=M(nf,function(a,b,c){b=K(vd,b,!0);if(b!=null&&b.length)for(B(a,c,2),tc(a.g,b.length*4),c=0;c<b.length;c++){var d=a.g;Wa(b[c]);z(d,v)}},
Ae),uf=L(function(a,b,c,d){if(a.h!==5)return!1;me(b,c,d,jc(a.g));return!0},ef,Ae),vf=L(function(a,b,c){a.h!==0?a=!1:(N(b,c,hc(a.g)),a=!0);return a},ff,ye),wf=M(function(a,b,c){a.h!==0&&a.h!==2?a=!1:(b=de(b,c),a.h==2?Ec(a,hc,b):b.push(hc(a.g)),a=!0);return a},function(a,b,c){b=K(Bd,b,!1);if(b!=null&&b.length){c=Hc(a,c);for(var d=0;d<b.length;d++){var e=b[d];switch(typeof e){case "number":var f=a.g;Ua(e);sc(f,v,x);break;case "bigint":e=qb(e);sc(a.g,e.h,e.g);break;default:e=rb(e),sc(a.g,e.h,e.g)}}Ic(a,
c)}},ye),xf=L(function(a,b,c,d){a.h!==0?a=!1:(me(b,c,d,hc(a.g)),a=!0);return a},ff,ye),yf=L(function(a,b,c){return of(a,b,c)},gf,ze),zf=L(function(a,b,c){return of(a,b,c)},gf,ze),Q=L(function(a,b,c){if(a.h!==0)return!1;N(b,c,dc(a.g));return!0},hf,xe),Af=M(pf,function(a,b,c){b=K(zd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,0),uc(e.g,g))}},xe),Bf=M(pf,function(a,b,c){b=K(zd,b,!0);if(b!=null&&b.length){c=Hc(a,c);for(var d=0;d<b.length;d++)uc(a.g,b[d]);Ic(a,c)}},
xe),Cf=L(function(a,b,c,d){if(a.h!==0)return!1;me(b,c,d,dc(a.g));return!0},hf,xe),R=L(function(a,b,c){if(a.h!==0)return!1;N(b,c,lc(a.g));return!0},jf,ve),Df=M(qf,function(a,b,c){b=K(wd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,0),e.g.g.push(g?1:0))}},ve),Ef=M(qf,function(a,b,c){b=K(wd,b,!0);if(b!=null&&b.length)for(B(a,c,2),tc(a.g,b.length),c=0;c<b.length;c++)a.g.g.push(b[c]?1:0)},ve),Ff=L(function(a,b,c,d){if(a.h!==0)return!1;me(b,c,d,lc(a.g));return!0},jf,ve),
T=L(function(a,b,c){if(a.h!==2)return!1;N(b,c,Cc(a));return!0},kf,we),Gf=L(function(a,b,c,d){if(a.h!==2)return!1;me(b,c,d,Cc(a));return!0},kf,we),U=M(function(a,b,c){if(a.h!==2)return!1;a=Cc(a);ee(b,b[C]|0,c).push(a);return!0},function(a,b,c){b=K(Fd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&Kc(e,f,Cb(g))}},we),V,Hf=void 0;Hf=Hf===void 0?ue:Hf;
V=new Ee(function(a,b,c,d,e){if(a.h!==2)return!1;d=Sd(void 0,d);ee(b,b[C]|0,c).push(d);Bc(a,d,e);return!0},function(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)lf(a,b[f],c,d,e);a=b[C]|0;a&1||E(b,a|1)}},Hf);
var W=Fe(function(a,b,c,d,e,f){if(a.h!==2)return!1;var g=b[C]|0;le(b,g,f,c,kd(g));b=ne(b,d,c);Bc(a,b,e);return!0},lf),If=L(function(a,b,c){if(a.h!==2)return!1;N(b,c,Dc(a));return!0},function(a,b,c){b=Dd(b);b!=null&&Kc(a,c,$b(b,!0).buffer)},Ce),X=L(function(a,b,c){if(a.h!==0)return!1;N(b,c,ec(a.g));return!0},function(a,b,c){b=Ad(b);b!=null&&b!=null&&(B(a,c,0),tc(a.g,b))},J()),Y=L(function(a,b,c){if(a.h!==0)return!1;N(b,c,dc(a.g));return!0},mf,De),Jf=M(function(a,b,c){if(a.h!==0&&a.h!==2)return!1;b=
de(b,c);a.h==2?Ec(a,mc,b):b.push(dc(a.g));return!0},function(a,b,c){b=K(zd,b,!0);if(b!=null)for(var d=0;d<b.length;d++)Jc(a,c,b[d])},De),Kf=L(function(a,b,c,d){if(a.h!==0)return!1;me(b,c,d,dc(a.g));return!0},mf,De),Lf=M(function(a,b,c){if(a.h!==0&&a.h!==2)return!1;b=de(b,c);a.h==2?Ec(a,fc,b):b.push(fc(a.g));return!0},function(a,b,c){b=K(zd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,0),tc(e.g,(g<<1^g>>31)>>>0))}},J()),Mf=[!0,T,Q],Nf=[!0,T,R],Of=[!0,T,T];function Pf(a){return function(b){var c=new Fc;af(b.l,c,Re(Ke,Ye,Ze,a));Gc(c,c.g.end());b=new Uint8Array(c.h);for(var d=c.i,e=d.length,f=0,g=0;g<e;g++){var h=d[g];b.set(h,f);f+=h.length}c.i=[b];return b}};var Qf=[0,L(function(a,b,c){if(a.h!==1)b=!1;else{var d=a.g;a=ic(d);d=ic(d);N(b,c,$a(a,d));b=!0}return b},function(a,b,c){b=Cd(b);if(b!=null)switch(Mc(b),B(a,c,1),a=a.g,Mc(b),typeof b){case "number":b<0?(c=fb(kb(-b)),b=c.g,z(a,c.h),z(a,b)):(Ta(b),z(a,v),z(a,x));break;case "bigint":c=b<BigInt(0)?fb(gb(-b)):gb(b);b=c.g;z(a,c.h);z(a,b);break;default:c=b.length&&b[0]==="-"?fb(nb(b.substring(1))):nb(b),b=c.g,z(a,c.h),z(a,b)}},J()),-1];var Rf=[0,L(function(a,b,c){if(a.h!==5)return!1;a=a.g;var d=a.h,e=a.g,f=d[e],g=d[e+1],h=d[e+2];d=d[e+3];cc(a,a.g+4);N(b,c,f<<0|g<<8|h<<16|d<<24);return!0},function(a,b,c){b=zd(b);b!=null&&(B(a,c,5),a=a.g,a.g.push(b>>>0&255),a.g.push(b>>>8&255),a.g.push(b>>>16&255),a.g.push(b>>>24&255))},J()),-1];var Sf=[0,Y,-1,vf,T,Rf,-1,O,Q,Y,Qf,T,Y,-1,[0,Rf,-1],Q,zf,Qf,O,[0,1,Q,-4,rf,[0,O,-1,Q],T,O,V,[0,Y,Q],Q,-1,Y,-2,O,-1,Y,O,Y,Q,[0,3,Q,-1,4,M(function(a,b,c){if(a.h!==2)return!1;a=Dc(a);ee(b,b[C]|0,c).push(a);return!0},function(a,b,c){b=K(Dd,b,!1);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&Kc(e,f,$b(g,!0).buffer)}},Ce)],rf,X,[0,Y,-1,T],R],T,Jf,V,[0,Qf,V,[0,T,Y],O,Y,-1],1,V,[0,zf,-1,X],Y,Qf];var Tf=[0,vf,[0,O,T,Q,T,Q,Af,vf,T,Q,T,-1,O,Q,O],If,[0,M(function(a,b,c){if(a.h!==1&&a.h!==2)return!1;b=de(b,c);if(a.h==2){c=a.g;a=ec(a.g)/8;var d=c.g,e=8*a;if(d+e>c.i)throw Error();var f=c.h;d+=f.byteOffset;qc===void 0&&(qc=(new Uint16Array((new Uint8Array([1,2])).buffer))[0]==513);if(qc)for(c.g+=e,c=new Float64Array(f.buffer.slice(d,d+e)),a=0;a<c.length;a++)b.push(c[a]);else for(e=0;e<a;e++)b.push(kc(c))}else b.push(kc(a.g));return!0},function(a,b,c){b=K(vd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=
a,f=c,g=b[d];g!=null&&(B(e,f,1),e=e.g,Xa(g),z(e,v),z(e,x))}},Be),-1]];function pe(a){this.l=F(a,void 0,void 0,2048)}p(pe,I);function Uf(a){a=ae(a,1,ge);return a==null?Wb():a}function Vf(a){var b=16E3;b=b===void 0?0:b;a=zd(ae(a,2));return a!=null?a:b};function Wf(a){this.l=F(a,void 0,void 0,2048)}p(Wf,I);function Xf(a){this.l=F(a,void 0,void 0,2048)}p(Xf,I);var Yf=[0,If,Q];var Zf=[0,[1,2,3,4],Gf,Kf,W,[0,T,Y],Kf];var $f=[0,T,-2,3,O,T,U,Y,-1,V,Zf,T,-2];var ag=[0,Q,-3];var bg=[0,[1,2,3,4],Ff,-1,Gf,-1];var eg=[0,T,-1,1,T,-1,6,U,[0,X,T,X,Q,X,-4,O,X,O,-1],R,U,-1];var Z=[0,Y,-5];var fg=[0,[0,T,-5,R,U,Z],T,-7,R,T,U,Z];var gg=[0,U,1,Y,-1,T];var hg=[0,T,-2,Z,T];var ig=[0,T,-1,R,T,U,Z];var jg=[0,V,[0,T,-1],T,R,T];var kg=[0,T,-2,Z];var lg=[0,T,-3,Q,T,R,T,-1,R,T,U,Z,T,-2];var mg=[0,R,T,-3,Q,T,R,T,U,Z];var ng=[0,T,-3,Q,T,-3,R,T,U,Z];var og=[0,T,Q,Y,T];var pg=[0,T,-2,Q,T,R,T,R,U,Z];var qg=[0,T,-2,R];var rg=[0,mg,pg,ig,T,Q,T,R,T,U,Z];var sg=[0,mg,vf,T,Q,T,R,T,U,Z,T];var tg=[0,T,-1,R,T,U,Z,R];var ug=[0,T,Q,R];var vg=[0,T,U,T,Q,T,R,T,U,Z];var wg=[0,Q,-2,R,T,Q,T,Q,T,R,T,U,Z,R];var xg=[0,Y,-1];var yg=[0,O,-1];var zg=[0,V,[0,O,-2],O,-1,Q,V,[0,Q,Y,Q,Y,X,Y,-1,V,yg,[0,O,-1],[0,V,yg,O,Y],[0,V,yg,Y]],O];var Ag=[0,O,-2];var Bg=[-11,{},ag,T,[0,Ef,Bf,P,U,V,[0,P],[0,P]],P,T,-1,[0,Ag],T,[0,P,-1,V,[0,Y,Q]],-1];var Cg=[0,ag,[0,R,O,P,-1],Q,[0,P]];var Dg=[0,Q,-2];var Eg=[0,Y,[0,Af,wf]];var Fg=[0,Y,[0,Af,U]];var Gg=[0,Q,-1,Y,Q];var Hg=[0,P,Bf];var Ig=[0,P,Bf,T];var Jg=[0,[0,yf,Y,R]];var Kg=[0,Q,-2,T];var Lg=[0,Y];var Ng=[-15,{},V,[-45,{},[1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,18,19,21,25,32,36,37,41],Gf,T,W,ig,W,tg,W,mg,W,pg,W,wg,W,rg,W,lg,W,fg,W,vg,W,sg,W,ng,W,jg,Gf,-1,V,qg,Gf,-1,zg,uf,[0,R,-1,Y,xg,R,-1,O,R,U,Gg,Y,-1],Sf,R,W,[0,T,-1],V,[0,T,-1],[0,U,R],Z,Y,Lg,R,W,ug,T,U,T,W,kg,W,hg,T,-1,R,W,og,R,Kg,T],V,[0,T,V,[0,T,-1,Y],V,[0,T,-1],T,Y,[0,Y,-3],U,R,T],4,Lg,O,R,function(){return Mg},T,Jg,R,[0,R,-1]],Mg=[0,V,function(){return Ng},-1];var Og=function(a,b){return function(c,d){var e={S:!0};d&&Object.assign(e,d);c=wc(c,void 0,void 0,e);try{var f=new a,g=f.l;Ve(b)(g,c);var h=f}finally{yc(c)}return h}}(Xf,[0,Y,2,Yf,Y,[-500,{},zf,T,Ng,-1,1,[0,Y,Q,-1,O],[0,T,-5,Q,T,1,R,-1,T,Y,V,$f,T],vf,-2,89,[-5,{},V,[-75,{},ag,X,-1,T,Y,T,-2,R,O,Y,T,R,-1,5,ig,tg,T,mg,pg,wg,rg,mg,lg,fg,vg,sg,ng,T,-1,kg,T,hg,1,jg,og,[0,T,-1],V,qg,7,eg,1,T,R,T,R,ug,T,R,T,-2,bg,T,R,O,U,1,T,R,1,T,gg,Y,R],V,[-71,{},ag,Y,T,-1,R,1,T,Y,eg,O,Y,R,Jf,T,xg,1,Q,R,1,T,Y,O,[0,[0,O,
-2],[0,O,-2]],[0,Y,-2],25,zg,T,3,R,-1,1,R,T,2,R,bg,T,Y,O,T,-1,1,T],V,[-11,{},ag,T,Y,5,[0,Q,-3],T],V,[-12,{},ag,T,R,O,-1,[0,O,-6,V,[0,T,Y,O]],tf,Q,-1,T,[0,[0,Q,-3],V,[0,T,O]]]],1,[0,3,V,[0,V,Dg,Dg],R],3,Gg,Y,-1,1,[-12,{},Gg,Y,-1,[0,Y,2,Y,-1],Y,-1,T,3,[0,R,-2]],39,[0,[0,Q,-2,Bf,-2],Fg,-2,Eg,Fg,-2,Eg,-5],49,[-3,{},[0,V,Bg,[0,V,[0,T,V,[0,Q,O,V,[0,Q,O,-1,Q],R],V,[0,Q,O],R,-2]]],V,[0,Q,V,[0,ag,[-10,{},Q,-2,X,[0,X,-2,O,-8,tf,-5,Lf,-1],Jf,Q,-2],Ag,O,-2,V,[0,Y,tf]]]],[-3,{},[0,V,Bg],V,[-6,{},V,Cg,V,Ag,Af,
Df,Bf]],48,[0,[0,V,Cg,Tf],[0,O,X,-1,O,X]],49,Yf,599,[-1,{}],R,[0,O,-2,Q],[-3,{},V,[-7,{},X,-1,R,V,[0,[1,2,3,4],W,[-5,{},Y,T,-1,R],W,[0],W,[0],W,[0]],O,X],X],Hg,V,Ig]]);var Pg=Pf($f);function Qg(a){this.l=F(a,void 0,void 0,2048)}p(Qg,I);var Rg=[1,4];function Sg(a){this.l=F(a,11,void 0,2048)}p(Sg,I);var Tg=[0,Q,If,Y];var Ug=[-11,{},[0,V,[0,Y,1,Y],Jf,Sf,U,V,[0,T,Y,O,Y],1,Y,-1,R],[0,T,-3,O,[0,Q,T],Jf,-1],[0,Rg,uf,[0,Y],[0,2,Y],Kf,[0,R,-1],O,Y,-2],[0,1,O,V,[0,T,-1],Jf,Jg,Q],gg,[-1,{}],[0,[1,3],W,[0,[3,4],V,Zf,-1,Cf,Ff,V,Zf],T,Gf],[0,[1,2,3,4,5,6,7,8,9,10,11],Kf,-10],[0,[1,2],[6],[3,4,5],W,Tg,W,Hg,W,Tg,W,Hg,W,[0,P],W,[0,Q,-1,R,O,-1]],[0,[1],W,Hg,V,Ig,Tg]];var Vg=[-3,{},T,Ug];function Wg(a){this.l=F(a,void 0,void 0,2048)}p(Wg,I);function Xg(a){this.l=F(a,5,void 0,2048)}p(Xg,I);function Yg(a){this.l=F(a,void 0,void 0,2048)}p(Yg,I);var Zg=[2,3,4];var $g=[0,T,-2];var ah=[0,[3,4],T,-1,xf,sf,Q,-1,T,-1];var bh=[0,Zg,Q,W,[-5,{},V,[0,[100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120],Q,T,-1,Ug,V,[0,[4,5],Q,T,-1,Kf,Gf,T,Ug,Y],T,-1,Kg,R,90,Gf,W,[0,T,Y,[0,Y,O,Y]],W,[0,T],W,[0,T,Q],W,[0,T,Y],W,[0,T,-1],W,[0,T,Y],W,ah,W,[0,1,T],W,$g,W,[0,U,Y],W,[0,[5,6,7],Q,-2,T,Kf,-1,Cf],W,[0,[5,6],Q,-3,Kf,Cf],W,[0,[1,2],[4,5,6],W,ah,W,$g,T,Kf,-1,Cf],W,[0,[3,4],[8,9,10],Q,-1,Cf,Gf,Q,Y,T,Kf,-1,Cf],W,[0,T,U,T],W,[0,[4,5,6],ah,T,1,Kf,-1,Cf],W,[0,T,-3,Q,T,-2],W,[0,T,Y],W,[0,V,[0,T,-1],T,
R],W,[0,T,-1]],Ug,V,[0,Q,-1,Ug],R],W,Vg,W,[0,[1,2],W,Tg,W,[0,T]]];var ch=[0,cf,Nf,cf,Mf,cf,Of];function dh(a){this.l=F(a,4,void 0,2048)}p(dh,I);var eh=[-4,{},V,bh,Ug,ch];function fh(a){this.l=F(a,3,void 0,2048)}p(fh,I);var gh=Pf([-3,{},V,Ng,eh]);function hh(a){a=a===void 0?new AudioContext({sampleRate:24E3}):a;this.h=!1;this.o=[];this.T={};this.M={};this.D={};this.N={};this.C={};this.Z=new TextEncoder;this.W="";this.I=null;this.J=0;this.K=[];this.H=this.u=this.B=this.j=!1;this.v=[];this.L=[];this.A=[];this.i=a;this.G=this.i.createGain()}aa=hh.prototype;
aa.init=function(a){var b=this;return t(function(c){switch(c.g){case 1:if(b.h)return c.return();b.h=!0;b.extensionId=a;return c.h(loadWasmTtsBindings(),2);case 2:return b.g=c.j,c.h(ih(b),3);case 3:return c.h(jh(b),4);case 4:return c.return(kh(b))}})};aa.onLanguageStatusRequest=function(a){var b=this,c,d;return t(function(e){return e.g==1?b.h?e.F(2):e.h(b.init(b.extensionId),2):e.g!=4?(c="offscreenLanguageStatusResponse",d=a,e.h(lh(b,a),4)):e.return({type:c,lang:d,status:e.j})})};
aa.onInstallLanguageRequest=function(a){var b=this,c,d;return t(function(e){return e.g==1?b.h?e.F(2):e.h(b.init(b.extensionId),2):e.g!=4?(c="offscreenLanguageStatusResponse",d=a,e.h(mh(b,a),4)):e.return({type:c,lang:d,status:e.j})})};aa.onUninstallLanguageRequest=function(a){var b=this,c;return t(function(d){if(d.g==1)return b.h?d.F(2):d.h(b.init(b.extensionId),2);if(d.g!=4)return d.h(nh(b,a),4);(c=d.j)&&oh(b);return d.return({type:"offscreenLanguageStatusResponse",lang:a,status:"notInstalled"})})};
function nh(a,b){var c,d,e,f,g,h;return t(function(k){switch(k.g){case 1:c=ph(a,b),d=!1,e=q(c),f=e.next();case 2:if(f.done){k.F(4);break}g=f.value;qh(a,g);if(!g.remote||g.unloaded){k.F(3);break}h="/voices/"+g.fileId;k.A(5);return k.h(rh(a,h),7);case 7:d=!0;k.B(3);break;case 5:k.v();case 3:f=e.next();k.F(2);break;case 4:return k.return(d)}})}
aa.onStop=function(a){var b=this,c;return t(function(d){if(!b.h)return d.return();sh(b);b.j=!1;b.B=!1;b.u=a;b.m&&(c={command:"clearBuffers"},b.m.port.postMessage(c),b.m.disconnect());for(th(b);b.L.length>0;)window.clearTimeout(b.L.pop());b.v=[];b.K.length=0;b.I=null;b.J=0;d.C()})};aa.onPause=function(){var a=this;return t(function(b){if(b.g==1){if(!a.h)return b.return();th(a);a.u=!0;return b.h(a.i.suspend(),2)}a.j=!1;b.C()})};
aa.onResume=function(){var a=this;return t(function(b){if(b.g==1){if(!a.h||a.j)return b.return();a.u=!1;return a.B?b.h(a.i.resume(),2):(a.A.length===0&&uh(a),b.return(vh(a)))}a.j=!0;wh(a);b.C()})};
aa.onSpeak=function(a,b){var c=this,d,e,f,g,h;return t(function(k){switch(k.g){case 1:return c.u=!1,k.h(c.init(c.extensionId),2);case 2:if(!c.g)throw Error("WASM module not initialized.");return b.voiceName?k.h(c.onStop(!1),3):k.return();case 3:c.utterance=a;d=b.voiceName;if(c.W===d){k.F(4);break}k.A(5);return k.h(xh(c,d,!1),7);case 7:e=c.D[d];if(!e)throw Error("Invalid voice name: "+b.voiceName);f=["/voices",e].join("/");g=[f,"pipeline.pb"].join("/");if(c.g){var m=yh(c,g);var n=yh(c,f),w=c.g._GoogleTtsInit(m,
n);c.g._free(n);c.g._free(m);m=w===1}else m=!1;if(!m)throw Error("Failed to initialize pipeline "+g);k.B(4);break;case 5:return k.v(),k.return(Promise.reject(Error("Voice is not available")));case 4:c.W=d;var y=b.lang;c.extensionId&&y&&chrome.runtime.sendMessage(c.extensionId,{type:"languageUsed",language:y});try{if(y=d,c.g&&a.length){var A=new Xg,G=new Wg;var D=ce(G,2,Ed(a));var S=te(A,[D]);var Fh=new Qg,Qb=b.rate;var Gh=ie(Fh,1,Rg,ud(!Qb||Qb<.1||Qb>10?1:Qb));var cg=b.pitch;m=ce(Gh,6,ud(cg?Math.pow(2,
(cg-1)*20/12):1));b.volume!==void 0&&b.volume>=0&&(c.G.gain.value=Math.min(Math.max(b.volume,0),1));n=new dh;w=new Yg;A=S;A=re(A);ie(w,2,Zg,A);A&&!cd(A)&&$d(w.l);var Hh=te(n,[w]);var Ih=new Sg;var Jh=se(Ih,3,m);var Kh=se(Hh,2,Jh);var Lh=new fh;var Mh=se(Lh,2,Kh);var gd=Array.from(new Uint8Array(gh(Mh))),Nh=c.N[y],Oh=new Wf;var Ph=ce(Oh,1,Ed(Nh));var hd=Pg(Ph),id=c.g._malloc(gd.length);c.g.HEAPU8.set(gd,id);var jd=c.g._malloc(hd.length);c.g.HEAPU8.set(hd,jd);var Qh=c.g._GoogleTtsInitBuffered(id,jd,
gd.length,hd.length);c.g._free(id);c.g._free(jd);if(!Qh)throw Error("Failed to initialize buffered synthesis.");uh(c)}}catch(dg){return h=dg instanceof Error?dg.message:"",k.return(Promise.reject(Error("Synthesis failed with "+h)))}k.C()}})};
function kh(a){return a.i.audioWorklet.addModule("../streaming_worklet_processor.js").then(function(){a.m=new AudioWorkletNode(a.i,"streaming-worklet-processor");a.m.port.onmessage=function(b){a.utterance&&!a.H&&b.data.type==="empty"&&(zh(a,{type:"end",charIndex:a.utterance.length}),a.onStop(!1))};a.G.connect(a.i.destination)})}function yh(a,b){b=a.Z.encode(b+"\x00");var c=a.g._malloc(b.length);a.g.HEAPU8.set(b,c);return c}
function uh(a){var b=setTimeout(function(){a.H=!0;var c=a.g,d=c._GoogleTtsReadBuffered();if(d===-1)zh(a,{type:"error"}),sh(a);else{for(var e=c._GoogleTtsGetTimepointsCount(),f=0;f<e;f++)Ah(a,{audioDeltaMillis:c._GoogleTtsGetTimepointsTimeInSecsAtIndex(f)*1E3,charIndex:Number(c._GoogleTtsGetTimepointsCharIndexAtIndex(f)),length:Number(c._GoogleTtsGetTimepointsCharLengthAtIndex(f))});f=c._GoogleTtsGetEventBufferPtr();e=c._GoogleTtsGetEventBufferLen();c=new Uint8Array(c.HEAPU8.buffer,f,e);c=Og(c.slice(0,
e));d=d===0;e=c.l;oe(e,e[C]|0)!==void 0?Bh(a,c,d):Ch(a,null);d?sh(a):uh(a)}},0);a.A.push(b)}function sh(a){a.H=!1;a.g._GoogleTtsFinalizeBuffered()}function th(a){for(;a.A.length>0;)window.clearTimeout(a.A.pop())}function Ah(a,b){var c=b.audioDeltaMillis,d=b.charIndex,e=b.length;d<0||c<=0||(a.j?c<-100||(c<2?zh(a,{type:"word",charIndex:d,length:e}):(c=window.setTimeout(function(){a.j?zh(a,{type:"word",charIndex:d,length:e}):a.v.push(b)},c),a.L.push(c))):a.v.push(b))}
function wh(a){var b=a.v;a.v=[];b=q(b);for(var c=b.next();!c.done;c=b.next())Ah(a,c.value)}function Bh(a,b,c){if(Vf(qe(b))===24E3){var d;b=(d=Uf(qe(b)))==null?void 0:new Uint8Array(Yb(d)||0);d=new Uint8Array(b);d=new Int16Array(d.buffer);d=Float32Array.from(d,function(e){return e/32768});Dh(a,d,c)}}
function Dh(a,b,c){for(var d=a.I,e=a.J,f=0,g=b.length;f<g;){var h=Math.min(128-e,g-f);d||(d=new Float32Array(128));d.set(b.subarray(f,f+h),e);f+=h;e+=h;e===128&&(Ch(a,d),e=0,d=null)}e!==0&&(c?Ch(a,d):(a.I=d,a.J=e))}function Ch(a,b){b&&a.K.push(b);if(a.m)for(;b=a.K.shift();)a.m.port.postMessage({command:"addBuffer",buffer:b}),a.B||a.u||vh(a)}function vh(a){return t(function(b){if(b.g==1)return a.m.connect(a.G),b.h(a.i.resume(),2);a.j=!0;a.B=!0;zh(a,{type:"start",charIndex:0});wh(a);b.C()})}
function lh(a,b){return t(function(c){return c.return(Eh(a,b,!1))})}function mh(a,b){return t(function(c){return c.return(Eh(a,b,!0))})}function Eh(a,b,c){var d,e,f;return t(function(g){switch(g.g){case 1:return d=ph(a,b),e=d.map(function(h){return xh(a,h.speakers[0].name,c)}),g.A(2),g.h(Promise.all(e),4);case 4:f="installed";c&&oh(a);g.B(3);break;case 2:g.v(),f=c?"failed":"notInstalled";case 3:return g.return(f)}})}
function ph(a,b){var c=b.toLowerCase();return c.includes("-")?a.o.filter(function(d){var e;return((e=d.language)==null?void 0:e.toLowerCase())===c}):a.o.filter(function(d){var e;return((e=d.language)==null?void 0:e.split("-")[0])===c})}
function Rh(a,b,c){var d,e,f,g,h,k,m,n,w,y;return t(function(A){if(!a.C[b])return A.return(Promise.resolve());d=a.C[b];f=q(Object.entries(a.M));for(g=f.next();!g.done;g=f.next())if(h=g.value,k=q(h),m=k.next().value,n=k.next().value,w=m,y=n,d===y){e=w;break}return e?A.return(xh(a,e,c)):A.return(Promise.reject(Error("No multivoice found for: "+b)))})}
function xh(a,b,c){var d,e,f,g,h,k;return t(function(m){switch(m.g){case 1:if(!a.g)return m.return(Promise.reject(Error("WASM module not initialized.")));m.A(2);return m.h(Rh(a,b,c),4);case 4:m.B(3);break;case 2:return d=m.v(),m.return(Promise.reject(Error(""+d)));case 3:e=a.D[b];if(!e)return m.return(Promise.reject(Error("Invalid voice name: "+b)));f=["/voices",e].join("/");g=[f,"pipeline.pb"].join("/");try{if(h=a.g.FS.stat(g))return m.return(Promise.resolve())}catch(n){}k=a.T[b];return c||k.indexOf("http")!==
0?m.return(fetch(k).then(function(n){return n.ok?n.arrayBuffer():Promise.reject(Error("Failed to fetch voice from url: "+k))}).then(function(n){if(!n)return Promise.reject(Error("Failed to fetch voice from url: "+k));if(!Sh(a,e,n))return Promise.reject(Error("Failed to validate voice data: "+e));try{a.g.FS.stat(f)}catch(G){a.g.FS.mkdir(f)}a.g.FS.stat(f);var w=yh(a,f),y=new Uint8Array(n),A=a.g._malloc(y.length);a.g.HEAPU8.set(y,A);n=a.g._GoogleTtsInstallVoice(w,A,n.byteLength);a.g._free(w);a.g._free(A);
return n!==1?Promise.reject(Error("Failed to install voice.")):new Promise(function(G,D){a.g.FS.syncfs(!1,function(S){S?D(S):G()})})})):m.return(Promise.reject(Error("Not downloading remote voice because caller did not request it.")))}})}function zh(a,b){a.extensionId&&chrome.runtime.sendMessage(a.extensionId,{type:"offscreenTtsEventResponse",event:b})}
function ih(a){var b,c;return t(function(d){if(d.g==1){if((b=a.g)==null||!b.FS)throw Error("WASM FS not ready for IDBFS setup.");try{a.g.FS.stat("/voices")}catch(e){a.g.FS.mkdir("/voices")}d.A(2);return d.h(new Promise(function(e,f){a.g.FS.mount(a.g.IDBFS,{},"/voices");a.g.FS.syncfs(!0,function(g){g?f(g):e()})}),4)}if(d.g!=2)return d.B(0);c=d.v();throw c;})}
function jh(a){var b,c,d;return t(function(e){switch(e.g){case 1:return e.A(2),e.h(fetch("voices.json"),4);case 4:b=e.j;if(!b.ok)throw Error("Failed to fetch voices.json: "+b.statusText+" ("+b.status+")");return e.h(b.json(),5);case 5:c=e.j;a.o=c;oh(a);e.B(0);break;case 2:throw d=e.v(),d;}})}
function oh(a){a.T={};a.M={};a.D={};a.N={};a.C={};for(var b={},c=q(a.o),d=c.next();!d.done;d=c.next()){d=d.value;for(var e=q(d.speakers),f=e.next();!f.done;f=e.next()){f=f.value;a.M[f.name]=d.id;a.D[f.name]=d.fileId;a.N[f.name]=f.speaker;d.dependentVoiceId&&(a.C[f.name]=d.dependentVoiceId);qh(a,d);a.T[f.name]=d.remote&&d.unloaded?d.url:"/"+d.id+".zvoice";var g=d.id.split("-");if(g.length<2)throw Error("Unexpected voice id format: "+d.id);g=g[0]+"-"+g[1].toUpperCase();d.language=g;d.remote&&d.unloaded||
(b[g]||(b[g]=[]),b[g].push(f.name))}}a.extensionId&&chrome.runtime.sendMessage(a.extensionId,{type:"offscreenVoicesResponse",voices:b})}function qh(a,b){try{a.g.FS.stat(["/voices",b.fileId].join("/")),b.unloaded=!1}catch(c){b.unloaded=!0}}
function rh(a,b){if(a.g)try{for(var c=a.g.FS.readdir(b),d=q(c),e=d.next();!e.done;e=d.next()){var f=e.value;f!=="."&&f!==".."&&a.g.FS.unlink(b+"/"+f)}a.g.FS.rmdir(b);return new Promise(function(g,h){a.g.FS.syncfs(!1,function(k){k?h(k):g()})})}catch(g){return Promise.resolve()}}function Sh(a,b,c){var d,e;return t(function(f){if(f.g==1)return f.h(Th(c),2);d=f.j;e=a.o.find(function(g){return g.fileId===b});return f.return(e!==void 0&&e.sha256Checksum===d&&e.compressedSize===c.byteLength)})}
function Th(a){var b,c,d,e;return t(function(f){if(f.g==1)return crypto&&crypto.subtle?f.h(crypto.subtle.digest("SHA-256",a),2):f.return("");b=f.j;c="";for(d=0;d<b.byteLength;d++)e=(new Uint8Array(b))[d],c+=Number(e>>4).toString(16),c+=Number(e&15).toString(16);return f.return(c)})}ea.Object.defineProperties(hh.prototype,{voices:{configurable:!0,enumerable:!0,get:function(){return this.o}}});var Uh=new hh,Vh=null;
chrome.runtime.onMessage.addListener(function(a,b,c){Vh||(Vh=Uh.init(b.id));Vh.then(function(){switch(a.type){case "init":Uh.init(b.id);c({result:"Initialized"});break;case "getLanguageStatus":Uh.onLanguageStatusRequest(a.lang).then(c);break;case "installLanguage":Uh.onInstallLanguageRequest(a.lang).then(c);break;case "uninstallLanguage":Uh.onUninstallLanguageRequest(a.lang).then(c);break;case "removeUnusedLanguage":nh(Uh,a.lang).then(function(){c({result:"Removed "+a.lang})});break;case "speak":Uh.onSpeak(a.utterance,
a.options);c({result:"Start speaking"});break;case "stop":Uh.onStop(!0);c({result:"Stopped speech"});break;case "pause":Uh.onPause();c({result:"Paused speech"});break;case "resume":Uh.onResume(),c({result:"Resumed speech"})}});return!0});
