"""
Chrome profile snapshot manager — Supabase Storage backend.

Uploads and downloads tarred Chrome profile directories so clones can start
with a pre-logged-in ChatGPT session without running auto_login or hitting 2FA.

Storage layout (Supabase Storage bucket: chrome-profiles):
    profile_0.tar.gz   ← account index 0
    profile_1.tar.gz   ← account index 1
    ...

Environment variables (required):
    BRANDSIGHT_SUPABASE_URL             Supabase project URL
    BRANDSIGHT_SUPABASE_SERVICE_KEY     Service role key — bypasses RLS and the
                                        50 MB per-file limit on the free tier.
                                        Falls back to BRANDSIGHT_SUPABASE_ANON_KEY
                                        if not set (uploads will fail unless bucket
                                        RLS policies allow anon inserts).

Environment variables (optional):
    CHROME_PROFILE_BUCKET               Bucket name (default: chrome-profiles)

Profile locking (Phase 4):
    The chatgpt_profiles table in Supabase tracks which worker holds which
    profile at any given time.  Postgres functions (defined in
    migrations/001_chatgpt_profiles.sql) provide atomic acquire / release /
    refresh operations using SELECT … FOR UPDATE SKIP LOCKED.

    acquire_profile()       — grab the next available slot, download it
    release_profile()       — give the slot back
    refresh_profile_lock()  — extend expiry + record last-upload timestamp
"""

from __future__ import annotations

import logging
import os
import shutil
import stat
import tarfile
import tempfile
from pathlib import Path

LOGGER = logging.getLogger(__name__)

BUCKET_NAME = os.getenv("CHROME_PROFILE_BUCKET", "chrome-profiles")

# When PROFILE_STORAGE_BACKEND=tigris the upload/download functions use S3
# (Fly Tigris) instead of Supabase Storage.  Set by fly-gpt-uk.yaml.
_STORAGE_BACKEND = os.getenv("PROFILE_STORAGE_BACKEND", "supabase")
_OBJECT_PREFIX = "profile_"

# Chrome subdirectories that are pure cache / ephemeral state and add bulk
# without helping session persistence. Stripping them keeps archives small.
# Goal: keep the archive under ~45 MB so it fits Supabase's free-tier limit.
# Only cookies, login data, preferences, and local-state files are essential
# for session persistence — everything else is regenerated on first visit.
_CACHE_DIRS = {
    # ── Explicit cache dirs ──────────────────────────────────────────────────
    "Cache",
    "Code Cache",
    "GPUCache",
    "DawnGraphiteCache",
    "DawnWebGPUCache",
    "ShaderCache",
    "GrShaderCache",
    "MediaCache",
    "Service Worker",  # large, regenerated on first visit
    "CacheStorage",
    # ── Web-app storage (not needed for cookie-based auth) ───────────────────
    "IndexedDB",  # web app databases — often huge, not auth-critical
    "blob_storage",  # binary blobs stored by web apps
    "databases",  # Web SQL databases
    "File System",  # HTML5 file system API storage
    "Session Storage",  # ephemeral per-tab storage, useless in snapshots
    "Local Storage",  # localStorage — regenerated by sites on next visit
    "Extension State",  # extension key-value store
    # ── Stats / telemetry (zero auth value) ─────────────────────────────────
    "VideoDecodeStats",
    "Heavy Ad Intervention",
    "Platform Notifications",
    "Pepper Data",
    "PnaclTranslationCache",
    "optimization_guide_model_metadata",
    "AutofillStrikeDatabase",
    "BudgetDatabase",
    "data_reduction_proxy_leveldb",
    "Download Service",
    "Reporting and NEL",
    "Site Characteristics Database",
    "Visited Links",
}

# Chrome process-specific files — meaningless in a snapshot
_SKIP_NAMES = {
    "SingletonLock",
    "SingletonSocket",
    "SingletonCookie",
    "lockfile",
    ".org.chromium.Chromium",
}


def _get_client(*, prefer_service_key: bool = True):
    """
    Return an initialised Supabase client.

    For uploads prefer the service role key so RLS doesn't block writes.
    Downloads work with the anon key if bucket policies permit.
    """
    from supabase import create_client

    url = os.getenv("BRANDSIGHT_SUPABASE_URL", "").strip()
    if not url:
        raise RuntimeError("BRANDSIGHT_SUPABASE_URL must be set to use the profile manager.")

    if prefer_service_key:
        key = os.getenv("BRANDSIGHT_SUPABASE_SERVICE_KEY", "").strip()
        if key:
            LOGGER.debug("Using service role key for Supabase Storage.")
        else:
            LOGGER.warning(
                "BRANDSIGHT_SUPABASE_SERVICE_KEY is not set — falling back to anon key. "
                "Uploads will fail if the bucket RLS policy blocks anon inserts. "
                "Set BRANDSIGHT_SUPABASE_SERVICE_KEY to fix this."
            )
            key = os.getenv("BRANDSIGHT_SUPABASE_ANON_KEY", "").strip()
    else:
        key = os.getenv("BRANDSIGHT_SUPABASE_ANON_KEY", "").strip()

    if not key:
        raise RuntimeError(
            "No Supabase key found. Set BRANDSIGHT_SUPABASE_SERVICE_KEY (preferred) or BRANDSIGHT_SUPABASE_ANON_KEY."
        )

    return create_client(url, key)


def _object_name(index: int) -> str:
    return f"{_OBJECT_PREFIX}{index}.tar.gz"


# ── Archive helpers ───────────────────────────────────────────────────────────


def _add_dir(tar: tarfile.TarFile, src: Path, arc_base: Path) -> None:
    """
    Recursively add src into the tar archive under arc_base, skipping:
      - sockets, FIFOs, device files (can't be archived)
      - Chrome singleton/lock files (process-specific)
      - Cache directories (bulk with no session value)
    """

    def _onerror(err: OSError) -> None:
        LOGGER.debug("Skipping unreadable path during walk: %s", err)

    for root, dirs, files in os.walk(str(src), followlinks=False, onerror=_onerror):
        root_path = Path(root)
        rel = root_path.relative_to(src)
        arc_dir = arc_base / rel

        # Prune cache dirs in-place so os.walk doesn't descend into them
        dirs[:] = [d for d in dirs if d not in _CACHE_DIRS]

        for filename in files:
            if filename in _SKIP_NAMES:
                LOGGER.debug("Skipping Chrome lock/singleton file: %s", filename)
                continue
            file_path = root_path / filename
            try:
                st = file_path.lstat()
                if not (stat.S_ISREG(st.st_mode) or stat.S_ISLNK(st.st_mode)):
                    LOGGER.debug("Skipping special file (%s): %s", stat.filemode(st.st_mode), file_path)
                    continue
                tar.add(str(file_path), arcname=str(arc_dir / filename), recursive=False)
            except OSError as exc:
                LOGGER.debug("Skipping %s: %s", file_path, exc)


# ── Upload ────────────────────────────────────────────────────────────────────


def upload_profile(index: int, profile_dir: str | Path) -> None:
    """
    Tar the given Chrome profile directory and upload it to storage.
    When PROFILE_STORAGE_BACKEND=tigris delegates to upload_profile_tigris.
    Otherwise uploads to Supabase Storage.  Existing objects are overwritten.
    """
    if _STORAGE_BACKEND == "tigris":
        upload_profile_tigris(index, profile_dir)
        return
    profile_dir = Path(profile_dir).expanduser()
    if not profile_dir.exists():
        raise FileNotFoundError(f"Chrome profile directory not found: {profile_dir}")

    object_name = _object_name(index)
    LOGGER.info("Archiving Chrome profile at %s → %s (excluding cache dirs) …", profile_dir, object_name)

    with tempfile.NamedTemporaryFile(suffix=".tar.gz", delete=False) as tmp:
        tmp_path = Path(tmp.name)

    try:
        with tarfile.open(tmp_path, "w:gz", compresslevel=9) as tar:
            _add_dir(tar, profile_dir, Path("chrome-profile"))

        size_mb = tmp_path.stat().st_size / 1_048_576
        LOGGER.info("Archive size: %.1f MB — uploading to bucket '%s' …", size_mb, BUCKET_NAME)

        if size_mb > 400:
            LOGGER.warning(
                "Archive is %.1f MB — this is large. Consider reviewing the "
                "_CACHE_DIRS exclusion list to trim unnecessary Chrome directories.",
                size_mb,
            )

        client = _get_client(prefer_service_key=True)
        with open(tmp_path, "rb") as f:
            data = f.read()

        # Try update (overwrite) first; fall back to upload (create) if not found
        try:
            client.storage.from_(BUCKET_NAME).update(
                object_name,
                data,
                {"content-type": "application/gzip"},
            )
            LOGGER.info("Overwrote existing profile object '%s'.", object_name)
        except Exception:
            client.storage.from_(BUCKET_NAME).upload(
                object_name,
                data,
                {"content-type": "application/gzip"},
            )
            LOGGER.info("Uploaded new profile object '%s'.", object_name)

    finally:
        tmp_path.unlink(missing_ok=True)

    LOGGER.info("✅ Profile %d uploaded successfully.", index)


# ── Download ──────────────────────────────────────────────────────────────────


def download_profile(index: int, dest_dir: str | Path) -> bool:
    """
    Download and extract profile_{index}.tar.gz.
    When PROFILE_STORAGE_BACKEND=tigris delegates to download_profile_tigris.
    Returns True on success, False if the object does not exist.
    """
    if _STORAGE_BACKEND == "tigris":
        return download_profile_tigris(index, dest_dir)
    dest_dir = Path(dest_dir).expanduser()
    object_name = _object_name(index)

    LOGGER.info("Downloading profile %d (%s) from bucket '%s' …", index, object_name, BUCKET_NAME)

    client = _get_client(prefer_service_key=True)

    try:
        data: bytes = client.storage.from_(BUCKET_NAME).download(object_name)
    except Exception as exc:
        LOGGER.warning("Profile %d not found in storage (will start with empty profile): %s", index, exc)
        return False

    dest_dir.mkdir(parents=True, exist_ok=True)

    with tempfile.NamedTemporaryFile(suffix=".tar.gz", delete=False) as tmp:
        tmp_path = Path(tmp.name)
        tmp.write(data)

    try:
        LOGGER.info("Extracting %.1f MB to %s …", len(data) / 1_048_576, dest_dir)
        with tarfile.open(tmp_path, "r:gz") as tar:
            for member in tar.getmembers():
                # Strip the leading "chrome-profile/" path component
                parts = Path(member.name).parts
                if len(parts) > 1:
                    member.name = str(Path(*parts[1:]))
                elif member.name in {"chrome-profile", "."}:
                    continue
                tar.extract(member, dest_dir, filter="data")
    finally:
        tmp_path.unlink(missing_ok=True)

    LOGGER.info("✅ Profile %d restored to %s.", index, dest_dir)
    return True


# ── Existence check ────────────────────────────────────────────────────────────


def profile_exists(index: int) -> bool:
    """Return True if profile_{index}.tar.gz exists in the bucket."""
    client = _get_client(prefer_service_key=True)
    try:
        files = client.storage.from_(BUCKET_NAME).list()
        names = {f["name"] for f in (files or [])}
        return _object_name(index) in names
    except Exception as exc:
        LOGGER.warning("Could not check profile existence: %s", exc)
        return False


# ── Profile locking (Phase 4) ─────────────────────────────────────────────────
# Calls Postgres RPC functions defined in migrations/001_chatgpt_profiles.sql.
# All functions use the service role key so RLS doesn't interfere.

_LOCK_HOURS_DEFAULT: float = 1.5  # Opt 3: reduced from 4.0 — locks refresh every ~30 min; 1.5h releases crashed-machine orphans sooner


def acquire_profile(
    worker_id: str,
    dest_dir: str | Path,
    lock_hours: float = _LOCK_HOURS_DEFAULT,
) -> dict[str, int | str] | None:
    """
    Atomically acquire an available Chrome profile from the DB, then download
    the snapshot to *dest_dir*.

    Returns a dict ``{"index": int, "email": str}`` on success, or ``None`` if
    all profiles are currently held by other workers.

    Raises on DB or network errors (so the caller can decide whether to abort
    or start with an empty profile).
    """
    client = _get_client(prefer_service_key=True)
    resp = client.rpc(
        "acquire_chatgpt_profile",
        {"p_worker_id": worker_id, "p_lock_hours": lock_hours},
    ).execute()

    rows = resp.data or []
    if not rows:
        LOGGER.warning("No available Chrome profile — all slots held by other workers.")
        return None

    row = rows[0]
    index: int = row["profile_index"]
    email: str = row["profile_email"]
    LOGGER.info("Acquired profile slot %d (%s) for worker %s.", index, email, worker_id)

    # Phase 2: download the snapshot (best-effort — new accounts start empty)
    ok = download_profile(index, dest_dir)
    if not ok:
        LOGGER.info(
            "No existing snapshot for profile %d — Chrome will start with an empty profile.",
            index,
        )

    return {"index": index, "email": email}


def release_profile(index: int, worker_id: str) -> bool:
    """
    Release a held profile lock.  Only the worker that acquired the lock can
    release it.  Returns True if the lock was released, False if it was not
    held by this worker (or had already expired).
    """
    try:
        client = _get_client(prefer_service_key=True)
        resp = client.rpc(
            "release_chatgpt_profile",
            {"p_index": index, "p_worker_id": worker_id},
        ).execute()
        released: bool = bool((resp.data or [False])[0])
        if released:
            LOGGER.info("Released profile slot %d.", index)
        else:
            LOGGER.warning(
                "Could not release profile slot %d — not held by worker %s (already expired?).",
                index,
                worker_id,
            )
        return released
    except Exception as exc:
        LOGGER.warning("Error releasing profile slot %d: %s", index, exc)
        return False


def set_profile_cooldown(
    index: int,
    worker_id: str,
    cooldown_hours: float = 2.0,
    reason: str = "rate_limit",
) -> bool:
    """
    Mark a profile as cooling down so acquire_chatgpt_profile skips it.

    Called when the worker detects a "too many requests" modal or repeated
    model downgrades from the same account.  The profile is automatically
    re-eligible after ``cooldown_hours``.

    Returns True if the cooldown was recorded, False on failure (non-fatal).
    """
    try:
        client = _get_client(prefer_service_key=True)
        resp = client.rpc(
            "set_chatgpt_profile_cooldown",
            {
                "p_index": index,
                "p_worker_id": worker_id,
                "p_cooldown_hours": cooldown_hours,
                "p_reason": reason,
            },
        ).execute()
        ok: bool = bool((resp.data or [False])[0])
        if ok:
            LOGGER.info(
                "Set cooldown on profile slot %d for %.1f h (reason=%s).",
                index,
                cooldown_hours,
                reason,
            )
        else:
            LOGGER.warning(
                "Could not set cooldown on profile slot %d — not held by worker %s.",
                index,
                worker_id,
            )
        return ok
    except Exception as exc:
        LOGGER.warning("Error setting cooldown on profile slot %d: %s", index, exc)
        return False


def refresh_profile_lock(
    index: int,
    worker_id: str,
    lock_hours: float = _LOCK_HOURS_DEFAULT,
) -> bool:
    """
    Extend the lock expiry for a held profile and record the current time as
    *last_uploaded_at*.  Should be called immediately after a successful
    Phase-3 upload so the machine's hold remains valid across long runs.

    Returns True if the refresh succeeded, False otherwise (non-fatal — the
    profile archive was already uploaded).
    """
    try:
        client = _get_client(prefer_service_key=True)
        resp = client.rpc(
            "refresh_chatgpt_profile_lock",
            {"p_index": index, "p_worker_id": worker_id, "p_lock_hours": lock_hours},
        ).execute()
        refreshed: bool = bool((resp.data or [False])[0])
        if refreshed:
            LOGGER.debug("Refreshed lock expiry for profile slot %d (%.1f h).", index, lock_hours)
        else:
            LOGGER.warning(
                "Could not refresh lock for profile slot %d — not held by worker %s.",
                index,
                worker_id,
            )
        return refreshed
    except Exception as exc:
        LOGGER.warning("Error refreshing profile lock for slot %d: %s", index, exc)
        return False


def acquire_profile_quality(
    worker_id: str,
    dest_dir: str | Path,
    lock_hours: float = _LOCK_HOURS_DEFAULT,
) -> dict[str, int | str] | None:
    """
    Quality-aware variant of acquire_profile. Prefers accounts with a higher
    historical gpt-5-5 success rate over equally-rested low-quality accounts.
    New accounts (no history) are treated as neutral (0.5 rate) and claimed
    before known-low-quality ones.

    Use for gpt-uk batches with required_models=[gpt-5-5, ...].
    Falls back to the same return shape as acquire_profile.
    """
    client = _get_client(prefer_service_key=True)
    resp = client.rpc(
        "acquire_chatgpt_profile_quality",
        {"p_worker_id": worker_id, "p_lock_hours": lock_hours},
    ).execute()

    rows = resp.data or []
    if not rows:
        LOGGER.warning("No available Chrome profile (quality-aware) — all slots held.")
        return None

    row = rows[0]
    index: int = row["profile_index"]
    email: str = row["profile_email"]
    LOGGER.info("Acquired profile slot %d (%s) via quality-aware claim for worker %s.", index, email, worker_id)

    ok = download_profile(index, dest_dir)
    if not ok:
        LOGGER.info("No existing snapshot for profile %d — Chrome will start empty.", index)

    return {"index": index, "email": email}


def update_session_stats(
    index: int,
    worker_id: str,
    gpt55_count: int,
    total_count: int,
) -> None:
    """
    Increment lifetime gpt-5-5 and total output counters for a profile after
    a session ends. Non-fatal — logging only on failure.

    Call at every session exit point (session cap, downgrade rotation, normal
    completion) so quality-aware claiming has accurate data next time.
    """
    if total_count <= 0:
        return
    try:
        client = _get_client(prefer_service_key=True)
        client.rpc(
            "update_profile_session_stats",
            {
                "p_index": index,
                "p_worker_id": worker_id,
                "p_gpt55_count": gpt55_count,
                "p_total_count": total_count,
            },
        ).execute()
        LOGGER.info(
            "Updated lifetime stats for profile slot %d: +%d gpt55 / +%d total.",
            index, gpt55_count, total_count,
        )
    except Exception as exc:
        LOGGER.warning("Could not update session stats for profile slot %d: %s", index, exc)


# ── Tigris (S3-compatible) storage ───────────────────────────────────────────
# Used when PROFILE_STORAGE_BACKEND=tigris (set in fly-gpt-uk.yaml).
# Credentials come from Fly secrets injected by `flyctl storage create`.

def _tigris_client():
    import boto3  # type: ignore[import]

    return boto3.client(
        "s3",
        endpoint_url=os.environ.get("AWS_ENDPOINT_URL_S3", "https://fly.storage.tigris.dev"),
        aws_access_key_id=os.environ["AWS_ACCESS_KEY_ID"],
        aws_secret_access_key=os.environ["AWS_SECRET_ACCESS_KEY"],
        region_name=os.environ.get("AWS_REGION", "auto"),
    )


def _tigris_bucket() -> str:
    return os.environ.get("BUCKET_NAME", "gpt-extractor-profiles")


def _profile_key(index: int) -> str:
    return f"chatgpt/profile_{index}.tar.gz"


def upload_profile_tigris(index: int, profile_dir: str | Path) -> None:
    """Archive and upload profile_{index} to Tigris (S3)."""
    profile_dir = Path(profile_dir).expanduser()
    if not profile_dir.exists():
        raise FileNotFoundError(f"Chrome profile directory not found: {profile_dir}")

    key = _profile_key(index)
    LOGGER.info("Archiving %s → Tigris/%s (excluding cache dirs) …", profile_dir, key)

    with tempfile.NamedTemporaryFile(suffix=".tar.gz", delete=False) as tmp:
        tmp_path = Path(tmp.name)

    try:
        with tarfile.open(tmp_path, "w:gz", compresslevel=9) as tar:
            _add_dir(tar, profile_dir, Path("chrome-profile"))

        size_mb = tmp_path.stat().st_size / 1_048_576
        LOGGER.info("Archive size: %.1f MB — uploading to Tigris …", size_mb)
        _tigris_client().upload_file(str(tmp_path), _tigris_bucket(), key)
        LOGGER.info("✅ Profile %d uploaded to Tigris (%s).", index, key)
    finally:
        tmp_path.unlink(missing_ok=True)


def download_profile_tigris(index: int, dest_dir: str | Path) -> bool:
    """Download profile_{index} from Tigris and extract it to dest_dir."""
    from botocore.exceptions import ClientError  # type: ignore[import]

    dest_dir = Path(dest_dir).expanduser()
    key = _profile_key(index)
    LOGGER.info("Downloading Tigris/%s → %s …", key, dest_dir)

    with tempfile.NamedTemporaryFile(suffix=".tar.gz", delete=False) as tmp:
        tmp_path = Path(tmp.name)

    try:
        try:
            _tigris_client().download_file(_tigris_bucket(), key, str(tmp_path))
        except ClientError as exc:
            if exc.response["Error"]["Code"] in ("NoSuchKey", "404"):
                LOGGER.warning("No profile in Tigris for index %d — fresh profile will be created.", index)
                return False
            raise

        dest_dir.mkdir(parents=True, exist_ok=True)
        size_mb = tmp_path.stat().st_size / 1_048_576
        LOGGER.info("Extracting %.1f MB to %s …", size_mb, dest_dir)
        with tarfile.open(tmp_path, "r:gz") as tar:
            for member in tar.getmembers():
                parts = Path(member.name).parts
                if len(parts) > 1:
                    member.name = str(Path(*parts[1:]))
                elif member.name in {"chrome-profile", "."}:
                    continue
                tar.extract(member, dest_dir, filter="data")
        LOGGER.info("✅ Profile %d restored from Tigris to %s.", index, dest_dir)
        return True
    finally:
        tmp_path.unlink(missing_ok=True)


def save_and_release(index: int, worker_id: str, profile_dir: str | Path) -> None:
    """
    Upload the current profile snapshot then release the DB lock.

    Called from entrypoint.sh EXIT trap so it fires on SIGTERM, script error,
    and normal exit. For hard failures (SIGKILL) the 4-hour lock_expires_at
    acts as the safety net.
    """
    profile_dir = Path(profile_dir).expanduser()
    LOGGER.info("Saving and releasing profile %d (worker %s) …", index, worker_id)

    if profile_dir.exists():
        try:
            if _STORAGE_BACKEND == "tigris":
                upload_profile_tigris(index, profile_dir)
            else:
                upload_profile(index, profile_dir)
            refresh_profile_lock(index, worker_id)
        except Exception as exc:
            LOGGER.warning("Profile upload failed (non-fatal — lock will auto-expire): %s", exc)
    else:
        LOGGER.warning("Profile dir %s not found — skipping upload.", profile_dir)

    release_profile(index, worker_id)


# ── Profile builder (local use only) ─────────────────────────────────────────


def build_profile(index: int, email: str) -> None:
    """
    Interactive profile builder — opens Chrome at chat.openai.com in a fresh
    (empty) local directory, waits for the user to sign in, then archives and
    uploads the result as profile_{index}.tar.gz.

    Intended for local developer use only (not run on Fly workers).

    Requires that Google Chrome is installed locally and that the
    ``undetected-chromedriver`` / ``selenium`` extras are available.
    """
    import subprocess
    import time

    LOGGER.info("Building profile %d for %s — opening Chrome at chat.openai.com …", index, email)

    # Use a stable named directory under /tmp (avoids TemporaryDirectory cleanup
    # issues with Chrome-locked files).
    profile_dir = Path(f"/tmp/chatgpt-profile-build-{index}")  # nosec B108 — ephemeral build dir for Chrome profile, index is an integer
    profile_dir.mkdir(parents=True, exist_ok=True)

    # Find the Chrome binary — no Selenium/undetected_chromedriver needed here
    # since we're running locally and the user controls login manually.
    chrome_candidates = [
        "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
        "/usr/bin/google-chrome",
        "/usr/bin/google-chrome-stable",
        "/usr/bin/chromium-browser",
    ]
    chrome_bin: str | None = None
    for candidate in chrome_candidates:
        if Path(candidate).exists():
            chrome_bin = candidate
            break
    if not chrome_bin:
        raise FileNotFoundError("Could not find Google Chrome. Install it or set the path manually.")

    LOGGER.info("Launching Chrome from %s …", chrome_bin)
    proc = subprocess.Popen(
        [
            chrome_bin,
            f"--user-data-dir={profile_dir}",
            "--no-first-run",
            "--no-default-browser-check",
            "--no-restore-last-session",
            "--disable-session-crashed-bubble",
            "--disable-infobars",
            "https://chatgpt.com",
        ],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )

    print()
    print("─" * 60)
    print("  Chrome has opened at chatgpt.com")
    print(f"  Sign in with:  {email}")
    print()
    print("  Once you can see the ChatGPT chat interface,")
    print("  come back here and press Enter to save the profile.")
    print("─" * 60)
    input("  Press Enter when logged in › ")
    print()

    LOGGER.info("Confirmed — closing Chrome and uploading profile …")

    # Graceful shutdown: let Chrome flush its profile data before we archive it.
    proc.terminate()
    try:
        proc.wait(timeout=8)
    except subprocess.TimeoutExpired:
        proc.kill()
        proc.wait()

    # Brief pause so any in-flight writes complete.
    time.sleep(2)

    # Archive and upload the profile.
    LOGGER.info("Uploading profile %d from %s …", index, profile_dir)
    upload_profile(index, profile_dir)

    # Clean up the local build directory.
    shutil.rmtree(profile_dir, ignore_errors=True)

    LOGGER.info("✅ Profile %d (%s) built and uploaded successfully.", index, email)


# ── CLI entry point ───────────────────────────────────────────────────────────


def main() -> None:
    """
    Standalone CLI for profile capture/restore/lock operations.

    Usage:
        # Storage commands
        python -m automated_extraction.profile_manager upload --index 0 --dir /path/to/profile
        python -m automated_extraction.profile_manager restore --index 0 --dest /tmp/chrome-profile
        python -m automated_extraction.profile_manager exists --index 0

        # Locking commands (require DB access via BRANDSIGHT_SUPABASE_SERVICE_KEY)
        python -m automated_extraction.profile_manager acquire --worker-id my-machine --dest /data/chrome-profile
        python -m automated_extraction.profile_manager release --index 2 --worker-id my-machine
        python -m automated_extraction.profile_manager refresh-lock --index 2 --worker-id my-machine

        # Interactive profile builder (local use only)
        python -m automated_extraction.profile_manager build --index 0 --email dev@theround.com
    """
    import argparse

    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

    parser = argparse.ArgumentParser(description="Chrome profile snapshot manager (Supabase Storage).")
    sub = parser.add_subparsers(dest="command", required=True)

    # ── Storage commands ──────────────────────────────────────────────────────
    up = sub.add_parser("upload", help="Archive and upload a Chrome profile directory.")
    up.add_argument("--index", type=int, required=True, help="Profile slot index (0, 1, 2 …).")
    up.add_argument("--dir", required=True, help="Path to the Chrome user data directory.")

    dl = sub.add_parser("restore", help="Download and extract a Chrome profile.")
    dl.add_argument("--index", type=int, required=True, help="Profile slot index.")
    dl.add_argument("--dest", required=True, help="Destination directory for the extracted profile.")

    ex = sub.add_parser("exists", help="Check whether a profile snapshot exists in storage.")
    ex.add_argument("--index", type=int, required=True, help="Profile slot index.")

    # ── Locking commands ──────────────────────────────────────────────────────
    acq = sub.add_parser(
        "acquire",
        help="Acquire the next available profile lock and download the snapshot.",
    )
    acq.add_argument("--worker-id", required=True, help="Unique identifier for this worker (e.g. FLY_MACHINE_ID).")
    acq.add_argument("--dest", required=True, help="Destination directory for the extracted profile.")
    acq.add_argument("--lock-hours", type=float, default=_LOCK_HOURS_DEFAULT, help="Lock duration in hours.")

    rel = sub.add_parser("release", help="Release a held profile lock.")
    rel.add_argument("--index", type=int, required=True, help="Profile slot index.")
    rel.add_argument("--worker-id", required=True, help="Worker ID that holds the lock.")

    rfr = sub.add_parser("refresh-lock", help="Extend lock expiry and record upload timestamp.")
    rfr.add_argument("--index", type=int, required=True, help="Profile slot index.")
    rfr.add_argument("--worker-id", required=True, help="Worker ID that holds the lock.")
    rfr.add_argument("--lock-hours", type=float, default=_LOCK_HOURS_DEFAULT, help="New lock duration in hours.")

    # ── Save + release (entrypoint EXIT trap) ─────────────────────────────────
    sar = sub.add_parser(
        "save-and-release",
        help="Upload the current profile to storage then release the DB lock. "
             "Called from entrypoint.sh EXIT trap.",
    )
    sar.add_argument("--index", type=int, required=True, help="Profile slot index.")
    sar.add_argument("--worker-id", required=True, help="FLY_MACHINE_ID of this worker.")
    sar.add_argument("--dir", required=True, help="Chrome profile directory to archive.")

    # ── Builder ───────────────────────────────────────────────────────────────
    bld = sub.add_parser(
        "build",
        help="Interactively build a Chrome profile: open Chrome, wait for login, upload snapshot.",
    )
    bld.add_argument("--index", type=int, required=True, help="Profile slot index to assign.")
    bld.add_argument("--email", required=True, help="ChatGPT account email for this profile slot.")

    args = parser.parse_args()

    from .config import load_dotenv_if_available

    load_dotenv_if_available()

    if args.command == "upload":
        upload_profile(args.index, args.dir)

    elif args.command == "restore":
        ok = download_profile(args.index, args.dest)
        if not ok:
            LOGGER.warning("No profile found for index %d — dest dir left empty.", args.index)

    elif args.command == "exists":
        found = profile_exists(args.index)
        print(f"Profile {args.index}: {'EXISTS' if found else 'NOT FOUND'}")

    elif args.command == "acquire":
        result = acquire_profile(args.worker_id, args.dest, lock_hours=args.lock_hours)
        if result:
            # Print parseable output for entrypoint.sh — stdout only, no other noise.
            # entrypoint.sh reads: "2 bob@theround.com"
            print(f"{result['index']} {result['email']}")
        else:
            # Non-zero exit so the caller knows no profile was obtained.
            raise SystemExit("No available Chrome profile — all slots are locked.")

    elif args.command == "release":
        released = release_profile(args.index, args.worker_id)
        if not released:
            raise SystemExit(f"Could not release profile {args.index} — not held by {args.worker_id}.")

    elif args.command == "refresh-lock":
        ok = refresh_profile_lock(args.index, args.worker_id, lock_hours=args.lock_hours)
        if not ok:
            LOGGER.warning("Lock refresh had no effect for profile %d / worker %s.", args.index, args.worker_id)

    elif args.command == "save-and-release":
        save_and_release(args.index, args.worker_id, args.dir)

    elif args.command == "build":
        build_profile(args.index, args.email)


if __name__ == "__main__":
    main()
